- makefile.shade
- src/Microsoft.AspNetCore.SignalR.Client.TS/EventSource.d.ts
fixes #13 
/cc @davidfowl @BrennanConroy @moozzyk 
/fyi @MisterJames
> install tsc during build

- src/Microsoft.AspNetCore.SignalR/JsonNetInvocationAdapter.cs
@anurse @davidfowl 
Fix nullref on connection close
> Null check for deserialize

- samples/ChatSample/Controllers/AccountController.cs
- samples/ChatSample/Models/AccountViewModels/LoginViewModel.cs
- samples/ChatSample/Models/AccountViewModels/RegisterViewModel.cs
- samples/ChatSample/Views/Account/Login.cshtml
- samples/ChatSample/Views/Account/Register.cshtml
> UserName and minor fixups for ChatSample

- .gitignore
- global.json
- src/Microsoft.AspNetCore.Sockets/HttpConnectionDispatcher.cs
- src/Microsoft.AspNetCore.Sockets/HttpDispatcherAppBuilderExtensions.cs
- src/Microsoft.AspNetCore.Sockets/WebSockets.cs
- src/Microsoft.AspNetCore.Sockets/project.json
- src/Microsoft.AspNetCore.WebSockets.Internal/WebSocketAppBuilderExtensions.cs
- test/Microsoft.AspNetCore.Sockets.Tests/HttpConnectionDispatcherTests.cs
- test/Microsoft.AspNetCore.Sockets.Tests/project.json
No automated tests yet, blocked on #26 (and functional tests which come after that). Also, could refactor for better (read: any) unit testing, but I want to get this merged. Logging an issue to improve WebSocket testing.
> integrate Channels-based WebSockets into SignalR

- src/Microsoft.AspNetCore.WebSockets.Internal/HandshakeHelpers.cs
Fixes #32 
We'll need tests for this when we do #29 
/cc @BrennanConroy
> fix #32 by handling connection header correctly

- src/Microsoft.AspNetCore.SignalR.Redis/RedisHubLifetimeManager.cs
@anurse @davidfowl @mikaelm12 @moozzyk 
Fix issue where user and group have the same name
> Add prefix to redis channel names

- samples/ChatSample/project.json
For issue: https://github.com/aspnet/SignalR/issues/38
@BrennanConroy @moozzyk @anurse @natemcmaster
> Fix EF dependencies

- src/Microsoft.AspNetCore.Sockets/WebSockets.cs
- test/Microsoft.AspNetCore.Sockets.Tests/WebSocketsTests.cs
- test/Microsoft.AspNetCore.Sockets.Tests/project.json
- test/Microsoft.Extensions.WebSockets.Internal.Tests/WebSocketPair.cs
also adds some error handling
/cc @BrennanConroy @moozzyk @mikaelm12 @davidfowl
> add tests to WebSockets transport

- samples/SocketsSample/Startup.cs
- src/Microsoft.AspNetCore.SignalR/SignalRDependencyInjectionExtensions.cs
- src/Microsoft.AspNetCore.Sockets/ConnectionManager.cs
- src/Microsoft.AspNetCore.Sockets/HttpDispatcherAppBuilderExtensions.cs
- src/Microsoft.AspNetCore.Sockets/SocketsDependencyInjectionExtensions.cs
- test/Microsoft.AspNetCore.Sockets.Tests/ConnectionManagerTests.cs
- test/Microsoft.AspNetCore.Sockets.Tests/HttpConnectionDispatcherTests.cs
- Added AddSockets extension method to IServiceCollection
- Inject IApplicationLifetime into ConnectionManager to handle
graceful shutdown and added test.
- Call AddSockets from AddSignalR
> DI enabled Microsoft.AspNetCore.Sockets

- test/Microsoft.AspNetCore.SignalR.Test.Server/project.json
- test/Microsoft.AspNetCore.Sockets.Tests/ConnectionManagerTests.cs
- test/Microsoft.AspNetCore.Sockets.Tests/HttpConnectionDispatcherTests.cs
- test/Microsoft.AspNetCore.Sockets.Tests/project.json
> Update project.json versions

- src/Microsoft.AspNetCore.Sockets/ConnectionManager.cs
- src/Microsoft.AspNetCore.Sockets/SocketsApplicationLifetimeEvents.cs
- src/Microsoft.AspNetCore.Sockets/SocketsDependencyInjectionExtensions.cs
- test/Microsoft.AspNetCore.Sockets.Tests/ConnectionManagerTests.cs
- test/Microsoft.AspNetCore.Sockets.Tests/HttpConnectionDispatcherTests.cs
- ConnectionManager now implements IApplicationEvents
> Clean up shutdown management

- SignalR.sln
> Remove hosting references

- samples/SocketsSample/wwwroot/hubs.html
@moozzyk @BrennanConroy @davidfowl
> Update SocketsSample 

- src/Microsoft.AspNetCore.SignalR.Common/IInvocationBinder.cs
- src/Microsoft.AspNetCore.SignalR.Common/InvocationMessage.cs
- src/Microsoft.AspNetCore.Sockets.Client/ITransport.cs
- src/Microsoft.AspNetCore.Sockets.Client/LongPollingTransport.cs
- src/Microsoft.AspNetCore.Sockets.Client/NullLoggerFactory.cs
- src/Microsoft.AspNetCore.Sockets.Client/PipelineConnection.cs
- src/Microsoft.AspNetCore.Sockets.Client/PipelineFactoryExtensions.cs
- src/Microsoft.AspNetCore.Sockets.Client/Utils.cs
- src/Microsoft.AspNetCore.Sockets/SocketsApplicationLifetimeService.cs
- src/Microsoft.AspNetCore.Sockets/SocketsDependencyInjectionExtensions.cs
- test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/Properties/AssemblyInfo.cs
- test/Microsoft.AspNetCore.SignalR.Tests/Properties/AssemblyInfo.cs
> Added Copyright and license headers

- samples/ChatSample/Hubs/Chat.cs
- samples/SocketsSample/Hubs/Chat.cs
- src/Microsoft.AspNetCore.SignalR.Client.TS/Transports.ts
- src/Microsoft.AspNetCore.SignalR.Client/HubConnection.cs
- src/Microsoft.AspNetCore.SignalR/Hub.cs
- src/Microsoft.AspNetCore.SignalR/HubEndPoint.cs
- src/Microsoft.AspNetCore.Sockets.Client/LongPollingTransport.cs
- test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs
- test/Microsoft.AspNetCore.SignalR.Tests/HubEndpointTests.cs
- test/Microsoft.AspNetCore.SignalR.Tests/project.json
> Handling exceptions thrown on the server side

- src/Microsoft.AspNetCore.SignalR/HubEndPoint.cs
re-removed error handling from HubEndpoint, since HttpConnectionDispatcher handles it
part of #105
> fix rebase error

- samples/SocketsSample/Hubs/Chat.cs
- samples/SocketsSample/wwwroot/hubs.html
- src/Microsoft.AspNetCore.SignalR.Redis/RedisHubLifetimeManager.cs
- src/Microsoft.AspNetCore.SignalR/DefaultHubLifetimeManager.cs
- src/Microsoft.AspNetCore.SignalR/HubEndPoint.cs
@davidfowl @anurse @moozzyk @mikaelm12
> Use connections format

- src/Microsoft.AspNetCore.SignalR.Redis/RedisHubLifetimeManager.cs
- src/Microsoft.AspNetCore.SignalR/DefaultHubLifetimeManager.cs
Avoids exceptions when connections are dead but still in the list.
> Use WaitToWriteAsync(), TryWrite() in HubLifetimeManager(s)

- test/Microsoft.AspNetCore.SignalR.Tests/EchoEndPoint.cs
- test/Microsoft.AspNetCore.SignalR.Tests/EndToEndTests.cs
- test/Microsoft.AspNetCore.SignalR.Tests/ServerFixture.cs
- test/Microsoft.AspNetCore.SignalR.Tests/project.json
Updated https://github.com/aspnet/SignalR/pull/94 in a new PR. 
@BrennanConroy @moozzyk @anurse @davidfowl
> Updated WebSockets tests

- samples/SocketsSample/wwwroot/polling.html
- samples/SocketsSample/wwwroot/sse.html
- src/Microsoft.AspNetCore.Sockets.Client/Connection.cs
- src/Microsoft.AspNetCore.Sockets/Connection.cs
- src/Microsoft.AspNetCore.Sockets/HttpConnectionDispatcher.cs
- src/Microsoft.AspNetCore.Sockets/Transports/LongPollingTransport.cs
- src/Microsoft.AspNetCore.Sockets/Transports/ServerSentEventsTransport.cs
- src/Microsoft.AspNetCore.Sockets/Transports/WebSocketsTransport.cs
- test/Microsoft.AspNetCore.Sockets.Tests/HttpConnectionDispatcherTests.cs
- test/Microsoft.AspNetCore.Sockets.Tests/ServerSentEventsTests.cs
also change SSE and Long Polling to require a pre-established connection and use http status codes instead of exceptions to report missing/unknown connection ids.
> rename getid to negotiate

- specs/TransportProtocols.md
Just something I missed in the comments for #125. Merging right away, just wanted to have this here for tracking/review purposes.
> Minor fix to transport protocol spec

- test/Microsoft.AspNetCore.SignalR.Tests/EndToEndTests.cs
@Tratcher @BrennanConroy @moozzyk
> Added a skip for Win7 and Win2008 for WebSockets testing

- src/Microsoft.AspNetCore.Sockets/IChannelConnection.cs
- src/Microsoft.AspNetCore.Sockets/Internal/ChannelConnection.cs
- src/Microsoft.AspNetCore.Sockets/Transports/LongPollingTransport.cs
- src/Microsoft.AspNetCore.Sockets/Transports/ServerSentEventsTransport.cs
- test/Microsoft.AspNetCore.SignalR.Tests/HubEndpointTests.cs
- test/Microsoft.AspNetCore.Sockets.Tests/LongPollingTests.cs
- test/Microsoft.AspNetCore.Sockets.Tests/ServerSentEventsTests.cs
- test/Microsoft.AspNetCore.Sockets.Tests/WebSocketsTests.cs
@anurse @moozzyk @davidfowl @mikaelm12
> React to Channel API changes

- src/Microsoft.AspNetCore.SignalR/HubEndPoint.cs
- Don't wait on the response of an invocation to pick up
the next message from the channel.
PS: I need to write a test
> Allow processing of incoming invocations in parallel

- src/Microsoft.AspNetCore.SignalR/HubEndPoint.cs
- src/Microsoft.AspNetCore.Sockets/HttpConnectionDispatcher.cs
- src/Microsoft.AspNetCore.Sockets/Internal/AwaitableThreadPool.cs
- test/Microsoft.AspNetCore.Sockets.Tests/HttpConnectionDispatcherTests.cs
- Execute EndPoint logic on a threadpool thread
- Turn synchronous exceptions into async ones to unify the
error handling
- Added tests
> Handle misbehaving user code

- src/Microsoft.AspNetCore.SignalR.Client.TS/HubConnection.ts
- src/Microsoft.AspNetCore.SignalR.Client.TS/Transports.ts
> Removed explicit capturing of "this" for lamdas

- src/Microsoft.AspNetCore.Sockets/ConnectionManager.cs
- Avoids overlapping Scans
- Noops if dispose is being called at the same time
> Use Monitor.TryEnter/Exit in the Scan loop

- test/Common/TaskExtensions.cs
- test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs
- test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/Microsoft.AspNetCore.SignalR.Client.FunctionalTests.csproj
- test/Microsoft.AspNetCore.SignalR.Tests/EndToEndTests.cs
- test/Microsoft.AspNetCore.SignalR.Tests/HubEndpointTests.cs
- test/Microsoft.AspNetCore.SignalR.Tests/Microsoft.AspNetCore.SignalR.Tests.csproj
- test/Microsoft.AspNetCore.Sockets.Client.Tests/ConnectionTests.cs
- test/Microsoft.AspNetCore.Sockets.Client.Tests/LongPollingTransportTests.cs
- test/Microsoft.AspNetCore.Sockets.Client.Tests/Microsoft.AspNetCore.Sockets.Client.Tests.csproj
- test/Microsoft.Extensions.WebSockets.Internal.Tests/Microsoft.Extensions.WebSockets.Internal.Tests.csproj
- test/Microsoft.Extensions.WebSockets.Internal.Tests/TestUtil.cs
- test/Microsoft.Extensions.WebSockets.Internal.Tests/WebSocketConnectionTests.ConnectionLifecycle.cs
- test/Microsoft.Extensions.WebSockets.Internal.Tests/WebSocketConnectionTests.PingPong.cs
- test/Microsoft.Extensions.WebSockets.Internal.Tests/WebSocketConnectionTests.ProtocolErrors.cs
- test/Microsoft.Extensions.WebSockets.Internal.Tests/WebSocketConnectionTests.ReceiveAsync.cs
- test/Microsoft.Extensions.WebSockets.Internal.Tests/WebSocketConnectionTests.SendAsync.cs
- test/Microsoft.Extensions.WebSockets.Internal.Tests/WebSocketConnectionTests.Utf8Validation.cs
For now I just use linked source. If there is more common utils to share we can create a common test project.
> Making `OrTimeout` common

- src/Microsoft.AspNetCore.Sockets.Client/Microsoft.AspNetCore.Sockets.Client.csproj
- src/Microsoft.AspNetCore.Sockets.Client/WebSocketsTransport.cs
- test/Microsoft.AspNetCore.SignalR.Tests/EndToEndTests.cs
Still a work in progress so not polished, but wanted to get some feedback.
> WebSockets Transport

- src/Microsoft.AspNetCore.Sockets.Common/TextMessageFormatter.cs
Will merge after we consume a new corefxlab build.
cc @pakrym @moozzyk
> React to API changes in System.Text.Primitives

- src/Microsoft.AspNetCore.Sockets.Client/Connection.cs
> Using webSockets transport as the default transport

- src/Microsoft.AspNetCore.SignalR/HubEndPoint.cs
- src/Microsoft.AspNetCore.SignalR/Internal/ObjectMethodExecutor.cs
- src/Microsoft.AspNetCore.SignalR/Microsoft.AspNetCore.SignalR.csproj
- src/Microsoft.AspNetCore.SignalR/Properties/AssemblyInfo.cs
- test/Microsoft.AspNetCore.SignalR.Tests/ObjectMethodExecutorTests.cs
> Use ObjectMethodExecutor for hub method invocations

- samples/ClientSample/HubSample.cs
- samples/ClientSample/RawSample.cs
- src/Microsoft.AspNetCore.SignalR.Client/HubConnection.cs
- src/Microsoft.AspNetCore.Sockets.Client/Connection.cs
- src/Microsoft.AspNetCore.Sockets.Client/ITransport.cs
- src/Microsoft.AspNetCore.Sockets.Client/LongPollingTransport.cs
- src/Microsoft.AspNetCore.Sockets.Client/WebSocketsTransport.cs
- test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs
- test/Microsoft.AspNetCore.SignalR.Tests/EndToEndTests.cs
- test/Microsoft.AspNetCore.Sockets.Client.Tests/ConnectionTests.cs
- test/Microsoft.AspNetCore.Sockets.Client.Tests/HubConnectionTests.cs
- test/Microsoft.AspNetCore.Sockets.Client.Tests/LongPollingTransportTests.cs
Converting StopAsync to DisposeAsync
> Removing Dispose from Transport, Connection and HubConnection

- src/Microsoft.AspNetCore.Sockets/Transports/WebSocketsTransport.cs
- src/Microsoft.Extensions.WebSockets.Internal/IWebSocketConnection.cs
- src/Microsoft.Extensions.WebSockets.Internal/Microsoft.Extensions.WebSockets.Internal.csproj
- src/Microsoft.Extensions.WebSockets.Internal/PipeReaderExtensions.cs
- src/Microsoft.Extensions.WebSockets.Internal/WebSocketConnection.cs
- test/Microsoft.AspNetCore.Sockets.Tests/Microsoft.AspNetCore.Sockets.Tests.csproj
- test/Microsoft.AspNetCore.Sockets.Tests/WebSocketsTests.cs
- test/Microsoft.Extensions.WebSockets.Internal.Tests/WebSocketConnectionTests.ConnectionLifecycle.cs
- test/Microsoft.Extensions.WebSockets.Internal.Tests/WebSocketConnectionTests.ProtocolErrors.cs
- test/Microsoft.Extensions.WebSockets.Internal.Tests/WebSocketConnectionTests.ReceiveAsync.cs
- test/Microsoft.Extensions.WebSockets.Internal.Tests/WebSocketConnectionTests.SendAsync.cs
- test/Microsoft.Extensions.WebSockets.Internal.Tests/WebSocketPair.cs
This should properly clean up the Pipes.
Fixes #215 
/cc @davidfowl
> Fix #215 and restore tests

- src/Microsoft.Extensions.WebSockets.Internal/WebSocketConnection.cs
- test/Microsoft.Extensions.WebSockets.Internal.Tests/WebSocketConnectionTests.ConnectionLifecycle.cs
- test/Microsoft.Extensions.WebSockets.Internal.Tests/WebSocketConnectionTests.PingPong.cs
My hunch is that the lack of a Task.Run means things aren't yielding properly. If this doesn't de-flake things, I'm just gonna skip the dang test :).
/cc @moozzyk @mikaelm12
> one last try to get this test de-flaked

- src/Microsoft.AspNetCore.Sockets.Common/Formatters/BinaryMessageFormatter.cs
- src/Microsoft.AspNetCore.Sockets.Common/Formatters/MessageFormatter.cs
- src/Microsoft.AspNetCore.Sockets.Common/Formatters/ServerSentEventsMessageFormatter.cs
- src/Microsoft.AspNetCore.Sockets.Common/Formatters/TextMessageFormatter.cs
- src/Microsoft.AspNetCore.Sockets.Common/MessageFormat.cs
- src/Microsoft.AspNetCore.Sockets.Common/Microsoft.AspNetCore.Sockets.Common.csproj
- test/Microsoft.AspNetCore.Sockets.Client.Tests/HubConnectionTests.cs
- test/Microsoft.AspNetCore.Sockets.Common.Tests/Formatters/BinaryMessageFormatterTests.cs
- test/Microsoft.AspNetCore.Sockets.Common.Tests/Formatters/ServerSentEventsMessageFormatterTests.cs
- test/Microsoft.AspNetCore.Sockets.Common.Tests/Formatters/TextMessageFormatterTests.cs
- test/Microsoft.AspNetCore.Sockets.Common.Tests/MessageTestUtils.cs
fixes #204 
Another formatter/parser and tests. Still not wired up :).
> implemented server-sent events formatter

- src/Microsoft.AspNetCore.SignalR.Client/HubConnection.cs
- test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs
Needed an overload that took just a url and a logger factory. Seems like a primary case.
> Edit HubConnection constructors

- src/Microsoft.AspNetCore.Sockets.Client/Connection.cs
- src/Microsoft.AspNetCore.Sockets.Client/LongPollingTransport.cs
- src/Microsoft.AspNetCore.Sockets.Client/WebSocketsTransport.cs
- test/Microsoft.AspNetCore.Sockets.Client.Tests/ConnectionTests.cs
> Fixing a race DisposeAsync is called when StartAsync hasn't finished

- test/Microsoft.AspNetCore.SignalR.Tests/EndToEndTests.cs
- test/Microsoft.AspNetCore.SignalR.Tests/ServerFixture.cs
Hoping this will prevent random failures like build SignalR build 1155
> Increasing the timeout of host start

- .travis.yml
- appveyor.yml
> Setting node version on travis

- test/Microsoft.Extensions.WebSockets.Internal.Tests/WebSocketConnectionTests.SendAsync.cs
fixes #150
Mostly just to make @davidfowl happy.
> add additional test for 0-byte sends

- client-ts/Microsoft.AspNetCore.Client.SignalR.TS.Tests/Formatters.spec.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/Common.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/Connection.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/Formatters.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/Transports.ts
- client-ts/Microsoft.AspNetCore.SignalR.Test.Server/Microsoft.AspNetCore.SignalR.Test.Server.csproj
> Replacing onError with onClosed

- samples/ClientSample/RawSample.cs
> Client raw sample fix

- src/Microsoft.AspNetCore.SignalR/HubEndPoint.cs
- test/Microsoft.AspNetCore.SignalR.Tests/HubEndpointTests.cs
https://github.com/aspnet/SignalR/issues/333
@anurse @moozzyk @mikaelm12
> Allow overridden and new methods on hubs

- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/Connection.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/HubConnection.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/IConnection.ts
- client-ts/Microsoft.AspNetCore.SignalR.Test.Server/wwwroot/js/connectionTests.js
- client-ts/Microsoft.AspNetCore.SignalR.Test.Server/wwwroot/js/hubConnectionTests.js
- samples/SocketsSample/wwwroot/hubs.html
- samples/SocketsSample/wwwroot/sockets.html
> Introducing the IConnection interface

- build/dependencies.props
- client-ts/Microsoft.AspNetCore.SignalR.Test.Server/Microsoft.AspNetCore.SignalR.Test.Server.csproj
- samples/ChatSample/ChatSample.csproj
- samples/ClientSample/ClientSample.csproj
- samples/SocialWeather/SocialWeather.csproj
- samples/SocketsSample/SocketsSample.csproj
- samples/WebSocketSample/WebSocketSample.csproj
- src/Microsoft.AspNetCore.Sockets.Common/Internal/Formatters/BinaryMessageParser.cs
- src/Microsoft.AspNetCore.Sockets.Common/Internal/Formatters/ServerSentEventsMessageFormatter.cs
- src/Microsoft.AspNetCore.Sockets.Common/Internal/Formatters/TextMessageParser.cs
- src/Microsoft.Extensions.WebSockets.Internal/WebSocketConnection.cs
- test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/Microsoft.AspNetCore.SignalR.Client.FunctionalTests.csproj
- test/Microsoft.AspNetCore.SignalR.Client.Tests/Microsoft.AspNetCore.SignalR.Client.Tests.csproj
- test/Microsoft.AspNetCore.SignalR.Microbenchmarks/Microsoft.AspNetCore.SignalR.Microbenchmarks.csproj
- test/Microsoft.AspNetCore.SignalR.Tests/Microsoft.AspNetCore.SignalR.Tests.csproj
- test/Microsoft.AspNetCore.Sockets.Common.Tests/Microsoft.AspNetCore.Sockets.Common.Tests.csproj
- test/Microsoft.AspNetCore.Sockets.Tests/Microsoft.AspNetCore.Sockets.Tests.csproj
- test/Microsoft.AspNetCore.WebSockets.Internal.ConformanceTest/Autobahn/AutobahnTester.cs
- test/Microsoft.AspNetCore.WebSockets.Internal.ConformanceTest/Microsoft.AspNetCore.WebSockets.Internal.ConformanceTest.csproj
- test/Microsoft.Extensions.WebSockets.Internal.Tests/Microsoft.Extensions.WebSockets.Internal.Tests.csproj
- test/Microsoft.Extensions.WebSockets.Internal.Tests/WebSocketConnectionTests.SendAsync.cs
- test/WebSocketsTestApp/WebSocketsTestApp.csproj
@davidfowl @anurse @moozzyk @mikaelm12
> Convert to netcoreapp2.0

- src/Microsoft.AspNetCore.SignalR/Internal/ObjectMethodExecutor.cs
@anurse @davidfowl 
Refer to: https://github.com/aspnet/Mvc/pull/5913
> Port ObjectMethodExecutor race fix

- test/Microsoft.AspNetCore.SignalR.Tests/EndToEndTests.cs
- test/Microsoft.Extensions.WebSockets.Internal.Tests/WebSocketConnectionTests.ReceiveAsync.cs
https://github.com/aspnet/SignalR/issues/362
> React to CoreFx byte[] slice

- src/Microsoft.AspNetCore.SignalR.Client/Microsoft.AspNetCore.SignalR.Client.csproj
- src/Microsoft.AspNetCore.SignalR.Common/Microsoft.AspNetCore.SignalR.Common.csproj
- src/Microsoft.AspNetCore.SignalR.Redis/Microsoft.AspNetCore.SignalR.Redis.csproj
- src/Microsoft.AspNetCore.SignalR/Microsoft.AspNetCore.SignalR.csproj
- src/Microsoft.AspNetCore.Sockets.Client/Microsoft.AspNetCore.Sockets.Client.csproj
- src/Microsoft.AspNetCore.Sockets.Common/Microsoft.AspNetCore.Sockets.Common.csproj
- src/Microsoft.AspNetCore.Sockets/Microsoft.AspNetCore.Sockets.csproj
- src/Microsoft.AspNetCore.WebSockets.Internal/Microsoft.AspNetCore.WebSockets.Internal.csproj
- src/Microsoft.Extensions.WebSockets.Internal/Microsoft.Extensions.WebSockets.Internal.csproj
> Disable API Check

- specs/HubProtocol.md
Here's the first pass at the full SignalR Hub Protocol document.
/fyi @DamianEdwards
> SignalR Hub Protocol

- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/HttpClient.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/Transports.ts
- src/Microsoft.AspNetCore.Sockets/HttpConnectionDispatcher.cs
- test/Microsoft.AspNetCore.Sockets.Tests/HttpConnectionDispatcherTests.cs
> Removing legacy raw format for `send`

- samples/ClientSample/ClientSample.csproj
- samples/ClientSample/HubSample.cs
- samples/ClientSample/Program.cs
- samples/ClientSample/RawSample.cs
- samples/SocketsSample/EndPoints/MessagesEndPoint.cs
- samples/SocketsSample/Program.cs
- samples/SocketsSample/SocketsSample.csproj
- samples/SocketsSample/Startup.cs
- src/Microsoft.AspNetCore.Sockets/ConnectionManager.cs
It's a lot easier to use now. a) it doesn't spam the logs, b) it shuts down properly and c) you don't have to comment/uncomment to switch samples, also it should be easier to add new samples.
> clean up client sample

- src/Microsoft.AspNetCore.Sockets.Client/DefaultTransportFactory.cs
- src/Microsoft.AspNetCore.Sockets.Client/ServerSentEventsTransport.cs
- src/Microsoft.AspNetCore.Sockets.Common/Internal/Formatters/ServerSentEventsMessageFormatter.cs
- src/Microsoft.AspNetCore.Sockets.Common/Internal/Formatters/ServerSentEventsMessageParser.cs
- test/Microsoft.AspNetCore.SignalR.Tests/DefaultTransportFactoryTests.cs
- test/Microsoft.AspNetCore.SignalR.Tests/EndToEndTests.cs
- test/Microsoft.AspNetCore.Sockets.Common.Tests/Internal/Formatters/ServerSentEventsParserTests.cs
- ServerSentEventsTransport
- ServerSentEventsParser
- Some basic unit tests
> SSE Transport

- test/Microsoft.AspNetCore.WebSockets.Internal.ConformanceTest/Microsoft.AspNetCore.WebSockets.Internal.ConformanceTest.csproj
This PR removes all references to PlatformAbstractions.
Part of aspnet/PlatformAbstractions#50
> react to removal of PlatformAbstractions

- src/Microsoft.AspNetCore.Sockets.Client/ServerSentEventsTransport.cs
- test/Microsoft.AspNetCore.WebSockets.Internal.ConformanceTest/AutobahnTests.cs
Travis and AppVeyor will fail because there are changes in Universe blocked on the build.
> fix build broken by PlatformAbstractions

- test/Microsoft.AspNetCore.SignalR.Client.Tests/ConnectionTests.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/Microsoft.AspNetCore.SignalR.Client.Tests.csproj
- test/Microsoft.AspNetCore.SignalR.Tests/EndToEndTests.cs
- test/Microsoft.AspNetCore.SignalR.Tests/ServerFixture.cs
Should turn #415 into a test failure, but doesn't address the underlying issue (haven't been able to figure much out from the dump yet.
/cc @mikeharder @moozzyk
> more logging and timeouts

- src/Microsoft.AspNetCore.Sockets/SocketsApplicationLifetimeService.cs
- src/Microsoft.AspNetCore.Sockets/SocketsDependencyInjectionExtensions.cs
Reacting to https://github.com/aspnet/Hosting/pull/1051
This was the only usage in our repos.
> React to IHostedService namespace change

- .travis.yml
- appveyor.yml
- build/dependencies.props
- Addresses package downgrade warnings (https://github.com/aspnet/SignalR/issues/428)
> Upgrade StackExchange.Redis.StrongName to version 1.2.3

- build/dependencies.props
- test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs
- test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/Microsoft.AspNetCore.SignalR.Client.FunctionalTests.csproj
- test/Microsoft.AspNetCore.SignalR.Client.Tests/ConnectionTests.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/Microsoft.AspNetCore.SignalR.Client.Tests.csproj
- test/Microsoft.AspNetCore.SignalR.Client.Tests/TaskQueueTests.cs
- test/Microsoft.AspNetCore.SignalR.Common.Tests/Microsoft.AspNetCore.SignalR.Common.Tests.csproj
- test/Microsoft.AspNetCore.SignalR.Tests/DefaultTransportFactoryTests.cs
- test/Microsoft.AspNetCore.SignalR.Tests/Microsoft.AspNetCore.SignalR.Tests.csproj
- test/Microsoft.AspNetCore.Sockets.Common.Tests/Microsoft.AspNetCore.Sockets.Common.Tests.csproj
- test/Microsoft.AspNetCore.Sockets.Tests/ConnectionManagerTests.cs
- test/Microsoft.AspNetCore.Sockets.Tests/Microsoft.AspNetCore.Sockets.Tests.csproj
- test/Microsoft.AspNetCore.WebSockets.Internal.ConformanceTest/Microsoft.AspNetCore.WebSockets.Internal.ConformanceTest.csproj
- test/Microsoft.Extensions.WebSockets.Internal.Tests/Microsoft.Extensions.WebSockets.Internal.Tests.csproj
Part of https://github.com/aspnet/Coherence-Signed/issues/497.
Update to xunit 2.3 and vstest.console 15.3. 
Fix up any errors found by xunit.analyzers.
> Upgrade test framework versions and fix test issues

- src/Microsoft.AspNetCore.Sockets.Common/Internal/Formatters/MessageFormatUtils.cs
- src/Microsoft.AspNetCore.Sockets.Common/Internal/Formatters/ServerSentEventsMessageFormatter.cs
- src/Microsoft.AspNetCore.Sockets.Common/Internal/Formatters/TextMessageFormatter.cs
Verified locally, fixes the mirroring issue.
> react to corefxlabs changes

- samples/ClientSample/HubSample.cs
- src/Microsoft.AspNetCore.SignalR.Client/HubConnection.cs
- src/Microsoft.AspNetCore.SignalR.Client/HubConnectionExtensions.cs
- test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/HubConnectionExtensionsTests.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/HubConnectionProtocolTests.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/HubConnectionTests.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/TestConnection.cs
> Adding strongly typed Invoke and On overloads

- src/Microsoft.AspNetCore.Sockets.Common/Internal/Formatters/MessageFormatUtils.cs
- src/Microsoft.AspNetCore.Sockets.Common/Internal/Formatters/ServerSentEventsMessageFormatter.cs
- src/Microsoft.AspNetCore.Sockets.Common/Internal/Formatters/TextMessageFormatter.cs
port from `dev-gate`. Waiting on the Mirror to complete.
/cc @kichalla
> react to corefxlabs changes (#464)

- src/Microsoft.AspNetCore.Sockets/SocketsApplicationLifetimeService.cs
Reacting https://github.com/aspnet/Hosting/pull/1090.
> React to Hosting changes

- src/Microsoft.AspNetCore.SignalR.Http/HubRouteBuilder.cs
- src/Microsoft.AspNetCore.Sockets.Abstractions/DefaultConnectionContext.cs
- src/Microsoft.AspNetCore.Sockets.Http/HttpConnectionContextExtensions.cs
- src/Microsoft.AspNetCore.Sockets.Http/HttpConnectionDispatcher.cs
- src/Microsoft.AspNetCore.Sockets.Http/SocketRouteBuilder.cs
- test/Microsoft.AspNetCore.Sockets.Tests/ConnectionManagerTests.cs
- test/Microsoft.AspNetCore.Sockets.Tests/HttpConnectionDispatcherTests.cs
- Added a GetHttpContext() extension method on ConnectionContext
> Remove the RequestId from DefaultConnectionContext

- test/Microsoft.AspNetCore.SignalR.Tests/EndToEndTests.cs
Against the correct branch this time.
Reference #527.
> Skip flaky test

- build/dependencies.props
- src/Microsoft.AspNetCore.Sockets.Common/Microsoft.AspNetCore.Sockets.Common.csproj
Part of https://github.com/aspnet/Coherence-Signed/issues/533
> Lift M.ANC.Sockets.Common to .NET Standard 2.0

- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/HubConnection.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/IHubProtocol.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/JsonHubProtocol.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/Microsoft.AspNetCore.SignalR.Client.TS.csproj
- Mimics the .NET client structure wise
- Also adds a JsonHubProtocol implementation
> Added IHubProtocol to ts client

- samples/SocketsSample/wwwroot/hubs.html
The socket sample group send wasn't grabbing the message properly. Just a wrong id
> Fix SocketSample group send

- src/Microsoft.AspNetCore.SignalR/HubEndPoint.cs
- src/Microsoft.AspNetCore.SignalR/Internal/HubReflectionHelper.cs
- test/Microsoft.AspNetCore.SignalR.Tests/HubEndpointTests.cs
- test/Microsoft.AspNetCore.SignalR.Tests/HubReflectionHelperTests.cs
> Don't over-discover Hub methods

- src/Microsoft.AspNetCore.Sockets.Client.Http/HttpConnection.cs
Simplify delegate invoking
fixes #561
> Simplify delegate invoking

- samples/SocketsSample/wwwroot/hubs.html
- src/Microsoft.AspNetCore.SignalR.Http/HubRouteBuilder.cs
- src/Microsoft.AspNetCore.SignalR/HubEndPoint.cs
- src/Microsoft.AspNetCore.SignalR/Microsoft.AspNetCore.SignalR.csproj
- src/Microsoft.AspNetCore.SignalR/SignalRDependencyInjectionExtensions.cs
- src/Microsoft.AspNetCore.Sockets.Http/Microsoft.AspNetCore.Sockets.Http.csproj
- test/Microsoft.AspNetCore.SignalR.Tests/HubEndpointTests.cs
- test/Microsoft.AspNetCore.SignalR.Tests/MapSignalRTests.cs
- test/Microsoft.AspNetCore.SignalR.Tests/TestClient.cs
- test/Microsoft.AspNetCore.Sockets.Tests/HttpConnectionDispatcherTests.cs
Part of https://github.com/aspnet/SignalR/issues/552
> Add authorization per hub method

- src/Microsoft.AspNetCore.Sockets.Http/Internal/SocketLoggerExtensions.cs
- src/Microsoft.AspNetCore.Sockets.Http/Internal/Transports/WebSocketsTransport.cs
- test/Microsoft.AspNetCore.Sockets.Tests/WebSocketsTests.cs
> Ignore failed send after close (WebSockets)

- src/Microsoft.AspNetCore.SignalR/Microsoft.AspNetCore.SignalR.csproj
- src/Microsoft.AspNetCore.SignalR/SignalRSocketBuilderExtensions.cs
- src/Microsoft.AspNetCore.Sockets.Http/SocketRouteBuilder.cs
- src/Microsoft.AspNetCore.Sockets/SocketBuilderExtensions.cs
- test/Microsoft.AspNetCore.Sockets.Tests/MapEndPointTests.cs
https://github.com/aspnet/SignalR/issues/552
> Support Authorize attribute on EndPoints

- client-ts/Microsoft.AspNetCore.SignalR.Client.TS.Tests/HubConnection.spec.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/HubConnection.ts
- src/Microsoft.AspNetCore.SignalR.Client/HubConnection.cs
- src/Microsoft.AspNetCore.SignalR.Client/HubConnectionExtensions.cs
- src/Microsoft.AspNetCore.SignalR/HubEndPoint.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/HubConnectionProtocolTests.cs
- test/Microsoft.AspNetCore.SignalR.Tests/HubEndpointTests.cs
- test/Microsoft.AspNetCore.SignalR.Tests/TestClient.cs
https://github.com/aspnet/SignalR/issues/589
> Support non blocking send on client

- NuGet.config
- samples/ClientSample/RawSample.cs
- src/Microsoft.AspNetCore.SignalR.Client/HubConnection.cs
- src/Microsoft.AspNetCore.Sockets.Abstractions/IConnection.cs
- src/Microsoft.AspNetCore.Sockets.Client.Http/HttpConnection.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/ConnectionTests.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/HubConnectionExtensionsTests.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/HubConnectionTests.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/TestConnection.cs
- test/Microsoft.AspNetCore.SignalR.Tests/EndToEndTests.cs
Addresses issue: https://github.com/aspnet/SignalR/issues/605
> Make Client Side Event Handlers Async

- test/Microsoft.AspNetCore.Sockets.Tests/TestWebSocketConnectionFeature.cs
- test/Microsoft.AspNetCore.Sockets.Tests/WebSocketsTests.cs
- Remove timeout and closed the application when the transport closes.
Made some tweaks to TestWebSocketConnectionFeature as a result.
- This uncovered some interesting issues with the WebSocketTransport itself so
further refactoring is needed to make it a bit more solid (see https://github.com/aspnet/SignalR/tree/davidfowl/ws-refactor-more)
#618
> Fix flaky test

- src/Microsoft.AspNetCore.SignalR.Common/Internal/Formatters/BinaryMessageParser.cs
- src/Microsoft.AspNetCore.SignalR.Common/Internal/Formatters/TextMessageParser.cs
- src/Microsoft.AspNetCore.SignalR.Common/Internal/Protocol/IHubProtocol.cs
- src/Microsoft.AspNetCore.SignalR.Common/Internal/Protocol/JsonHubProtocol.cs
- src/Microsoft.AspNetCore.SignalR.Common/Internal/Protocol/MessagePackHubProtocol.cs
- src/Microsoft.AspNetCore.SignalR.Common/Internal/Protocol/NegotiationProtocol.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/HubConnectionTests.cs
- test/Microsoft.AspNetCore.SignalR.Common.Tests/Internal/Protocol/MessagePackHubProtocolTests.cs
- test/Microsoft.AspNetCore.SignalR.Microbenchmarks/MessageParserBenchmark.cs
- test/Microsoft.AspNetCore.SignalR.Tests/Formatters/BinaryMessageParserTests.cs
- test/Microsoft.AspNetCore.SignalR.Tests/Formatters/TextMessageParserTests.cs
- Changed parser input to ReadOnlySpan<byte> to ReadOnlyBuffer<byte>
> Make parsers stateless

- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/HttpClient.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/HttpError.ts
Addresses issue: https://github.com/aspnet/SignalR/issues/547
> Set X-Requested-With header

- samples/ClientSample/HubSample.cs
- src/Microsoft.AspNetCore.SignalR.Client/HubConnectionExtensions.cs
- test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/HubConnectionProtocolTests.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/HubConnectionTests.cs
Issue: https://github.com/aspnet/SignalR/issues/634
> Rename HubConnection Extension Methods from Invoke to InvokeAsync

- src/Microsoft.AspNetCore.Sockets.Client.Http/ServerSentEventsTransport.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/LongPollingTransportTests.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/ServerSentEventsTransportTests.cs
- test/Microsoft.AspNetCore.SignalR.Tests/EndToEndTests.cs
> Exiting SSE transport receive loop when transport is stopping

- src/Microsoft.AspNetCore.Sockets.Client.Http/HttpConnection.cs
- src/Microsoft.AspNetCore.Sockets.Client.Http/ITransport.cs
- src/Microsoft.AspNetCore.Sockets.Client.Http/Internal/SocketClientLoggerExtensions.cs
- src/Microsoft.AspNetCore.Sockets.Client.Http/LongPollingTransport.cs
- src/Microsoft.AspNetCore.Sockets.Client.Http/SendUtils.cs
- src/Microsoft.AspNetCore.Sockets.Client.Http/ServerSentEventsTransport.cs
- src/Microsoft.AspNetCore.Sockets.Client.Http/WebSocketsTransport.cs
- src/Microsoft.AspNetCore.Sockets.Http/Internal/SocketHttpLoggerExtensions.cs
- src/Microsoft.AspNetCore.Sockets/ConnectionManager.cs
- src/Microsoft.AspNetCore.Sockets/Internal/SocketLoggerExtensions.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/ConnectionTests.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/LongPollingTransportTests.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/ServerSentEventsTransportTests.cs
- test/Microsoft.AspNetCore.SignalR.Tests/EndToEndTests.cs
- test/Microsoft.AspNetCore.SignalR.Tests/Internal/DefaultHubProtocolResolverTests.cs
- test/Microsoft.AspNetCore.SignalR.Tests/WebSocketsTransportTests.cs
Part of https://github.com/aspnet/SignalR/issues/553
> Complete logging for Socket.* packages

- src/Microsoft.AspNetCore.Sockets.Client.Http/ServerSentEventsTransport.cs
Because https://travis-ci.org/aspnet/SignalR/jobs/253286760
> Accounting for ReadAsync throwing OperationCanceledException

- samples/SocketsSample/Hubs/DynamicChat.cs
- samples/SocketsSample/Startup.cs
- samples/SocketsSample/wwwroot/hubs.html
- samples/SocketsSample/wwwroot/index.html
- src/Microsoft.AspNetCore.SignalR/DynamicClientProxy.cs
- src/Microsoft.AspNetCore.SignalR/DynamicHub.cs
- src/Microsoft.AspNetCore.SignalR/DynamicHubClients.cs
- test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs
- test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/Hubs.cs
- test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/Microsoft.AspNetCore.SignalR.Client.FunctionalTests.csproj
- test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/Startup.cs
- test/Microsoft.AspNetCore.SignalR.Tests/HubEndpointTests.cs
- test/Microsoft.AspNetCore.SignalR.Tests/Microsoft.AspNetCore.SignalR.Tests.csproj
Part 2 of https://github.com/aspnet/SignalR/issues/554
I changed the SocketSample Chat hub to be a dynamic hub as well.
> Dynamic Hub Change Part 2

- src/Microsoft.AspNetCore.Sockets.Client.Http/HttpConnection.cs
- src/Microsoft.AspNetCore.Sockets.Client.Http/Internal/TaskExtensions.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/HttpConnectionTests.cs
Addresses issue: https://github.com/aspnet/SignalR/issues/585
> Add timeout to Event Queue drain

- src/Microsoft.AspNetCore.SignalR/DefaultHubLifetimeManager.cs
- src/Microsoft.AspNetCore.Sockets.Abstractions/Features/IConnectionTransportFeature.cs
- src/Microsoft.AspNetCore.Sockets.Abstractions/Features/IConnectionUserFeature.cs
- src/Microsoft.AspNetCore.Sockets.Http/HttpConnectionDispatcher.cs
- src/Microsoft.AspNetCore.Sockets.Http/Internal/Transports/WebSocketsTransport.cs
- src/Microsoft.AspNetCore.Sockets.Http/WebSocketOptions.cs
- src/Microsoft.AspNetCore.Sockets/DefaultConnectionContext.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/Microsoft.AspNetCore.SignalR.Client.Tests.csproj
- test/Microsoft.AspNetCore.Sockets.Tests/HttpConnectionDispatcherTests.cs
- test/Microsoft.AspNetCore.Sockets.Tests/WebSocketsTests.cs
(reopening after rebasing on dev)
> Support for binary protocols on the server side

- src/Microsoft.AspNetCore.Sockets.Http/Internal/AuthorizeHelper.cs
@davidfowl is there an appropriate resource to use for SignalR or is null sufficient?
> React to AuthZ change

- samples/SocketsSample/wwwroot/hubs.html
Not implemented yet. 
Being tracked here: https://github.com/aspnet/SignalR/issues/540
> Remove Send to Individual User in the SocketSample

- src/Microsoft.AspNetCore.Sockets.Client.Http/ServerSentEventsTransport.cs
- test/Microsoft.AspNetCore.SignalR.Tests/EndToEndTests.cs
> SSE StopAsync should ignore exception (handled elsewhere)

- build/dependencies.props
- test/Microsoft.AspNetCore.SignalR.Tests/HubEndpointTests.cs
beta3 fixes:
- navigation from test to code
- shortcuts (Ctrl+r, t etc.)
- adornments
> Updating xUnit version

- samples/ChatSample/Startup.cs
Making this change so that when someone using the sample wants to use the presence feature they just have to uncomment the the four lines and go
> Add using for presence in chat sample

- client-ts/Microsoft.AspNetCore.SignalR.Client.TS.Tests/Base64EncodedHubProtocol.spec.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/Base64EncodedHubProtocol.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/Formatters.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/HubConnection.ts
- src/Microsoft.AspNetCore.SignalR.Common/Internal/Encoders/Base64Encoder.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/HubConnectionProtocolTests.cs
... in preparation for pipeline conversion
> Length prefixing base64 encoded messages

- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/tsconfig.json
Fixes https://github.com/aspnet/SignalR/issues/416
> Changing module type to commonjs

- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/gulpfile.js
- client-ts/Microsoft.AspNetCore.SignalR.Test.Server/Microsoft.AspNetCore.SignalR.Test.Server.csproj
- client-ts/Microsoft.AspNetCore.SignalR.Test.Server/wwwroot/connectionTests.html
- client-ts/package-lock.json
- client-ts/package.json
Creating a minified version of javascript signalr client
> Minification - part 1

- client-ts/package-lock.json
- client-ts/package.json
> Making msgpack5 a prod dependency

- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/HttpClient.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/Transports.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/UserAgent.ts
Issue: https://github.com/aspnet/SignalR/issues/778
We should be sure to remember to run the browser tests smh
> Unset the UserAgent Header in the TS client

- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/Base64EncodedHubProtocol.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/Formatters.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/HubConnection.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/Transports.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/gulpfile.js
- client-ts/Microsoft.AspNetCore.SignalR.Test.Server/wwwroot/connectionTests.html
- client-ts/Microsoft.AspNetCore.SignalR.Test.Server/wwwroot/js/common.js
- client-ts/Microsoft.AspNetCore.SignalR.Test.Server/wwwroot/js/connectionTests.js
- client-ts/Microsoft.AspNetCore.SignalR.Test.Server/wwwroot/js/hubConnectionTests.js
- client-ts/Microsoft.AspNetCore.SignalR.Test.Server/wwwroot/js/webSocketTests.js
- client-ts/package-lock.json
- client-ts/package.json
Here are the sizes:
```
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        8/25/2017   4:42 PM          32339 signalr-client.js
-a----        8/25/2017   4:42 PM          14825 signalr-client.min.js
-a----        8/25/2017   4:42 PM         169458 signalr-clientES5.js
-a----        8/25/2017   4:42 PM          72055 signalr-clientES5.min.js
-a----        8/25/2017   4:42 PM         282224 signalr-msgpackprotocol.js
-a----        8/25/2017   4:42 PM         109505 signalr-msgpackprotocol.min.js
```
I also need to test ES5 versions on IE11 which is trickier than it sound since it requires transpiling the tests.
> Creating ES5 version of the TS client

- src/Microsoft.AspNetCore.SignalR.Redis/Internal/AckHandler.cs
- src/Microsoft.AspNetCore.SignalR.Redis/RedisHubLifetimeManager.cs
We'll probably want to factor this out of Redis and make it generic to HubLifetimeManager after alpha
https://github.com/aspnet/SignalR/issues/584
> Add Group Add and Remove acks

- src/Microsoft.AspNetCore.Sockets/ConnectionManager.cs
- src/Microsoft.AspNetCore.Sockets/Internal/SocketLoggerExtensions.cs
https://github.com/aspnet/SignalR/issues/548
> Log connection resets as trace not error

- client-ts/Microsoft.AspNetCore.SignalR.Client.TS.Tests/Base64EncodedHubProtocol.spec.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS.Tests/Common.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS.Tests/Connection.spec.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS.Tests/Formatters.spec.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS.Tests/HubConnection.spec.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS.Tests/JasmineUtils.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS.Tests/MessagePackHubProtocol.spec.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/Base64EncodedHubProtocol.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/Common.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/Formatters.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/HttpClient.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/HttpConnection.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/HttpError.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/HubConnection.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/IConnection.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/IHttpConnectionOptions.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/IHubProtocol.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/ILogger.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/JsonHubProtocol.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/Loggers.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/MessagePackHubProtocol.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/Observable.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/Transports.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/gulpfile.js
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/index.ts
- client-ts/Microsoft.AspNetCore.SignalR.Test.Server/wwwroot/js/common.js
- client-ts/Microsoft.AspNetCore.SignalR.Test.Server/wwwroot/js/connectionTests.js
- client-ts/Microsoft.AspNetCore.SignalR.Test.Server/wwwroot/js/hubConnectionTests.js
- client-ts/Microsoft.AspNetCore.SignalR.Test.Server/wwwroot/js/webSocketTests.js
Issue: https://github.com/aspnet/SignalR/issues/797
> Headers for TS files

- src/Microsoft.AspNetCore.SignalR.Core/DynamicHubClients.cs
- src/Microsoft.AspNetCore.SignalR.Core/IHubClients.cs
- src/Microsoft.AspNetCore.SignalR.Core/IHubClients`T.cs
- src/Microsoft.AspNetCore.SignalR.Core/TypedHubClients.cs
- test/Microsoft.AspNetCore.SignalR.Tests/HubEndpointTests.cs
AllExcept for the Dynamic and Strongly typed hubs.
> AllExcept for Dynamic and Typed Hubs

- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/ILogger.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/Transports.ts
- client-ts/Microsoft.AspNetCore.SignalR.Test.Server/wwwroot/js/connectionTests.js
- client-ts/Microsoft.AspNetCore.SignalR.Test.Server/wwwroot/js/hubConnectionTests.js
> Logging traffic at Trace level

- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/HubConnection.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/ILogger.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/Transports.ts
- client-ts/Microsoft.AspNetCore.SignalR.Test.Server/wwwroot/js/connectionTests.js
- client-ts/Microsoft.AspNetCore.SignalR.Test.Server/wwwroot/js/hubConnectionTests.js
> Client side method names should be case insensitive

- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/HubConnection.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/ILogger.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/Transports.ts
- client-ts/Microsoft.AspNetCore.SignalR.Test.Server/wwwroot/js/connectionTests.js
- client-ts/Microsoft.AspNetCore.SignalR.Test.Server/wwwroot/js/hubConnectionTests.js
- src/Microsoft.AspNetCore.SignalR.Core/HubOptions.cs
- test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/Hubs.cs
- test/Microsoft.AspNetCore.SignalR.Tests/SignalRDependencyInjectionExtensionsTests.cs
> Initializing HubOptions.JsonSerializationSettings to default settings

- test/Common/ServerFixture.cs
Hi guys, if of any interest, there is this small renaming needed in the ServerFixture class.
Of course just a minimal change, feel free to drop the PR if is not relevant for you.
Cheers
Livio
> Renamed private fields according to coding guidelines

- src/Microsoft.AspNetCore.SignalR/HttpConnectionContextExtensions.cs
- test/Microsoft.AspNetCore.SignalR.Tests/HubEndpointTests.cs
https://github.com/aspnet/SignalR/issues/837
> Add extension method to get HttpContext on HubConnectionContext

- client-ts/Microsoft.AspNetCore.SignalR.Client.TS.Tests/Connection.spec.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/HttpConnection.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/HubConnection.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/IHubConnectionOptions.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/Transports.ts
- client-ts/Microsoft.AspNetCore.SignalR.Test.Server/wwwroot/js/common.js
- client-ts/Microsoft.AspNetCore.SignalR.Test.Server/wwwroot/js/connectionTests.js
- client-ts/Microsoft.AspNetCore.SignalR.Test.Server/wwwroot/js/hubConnectionTests.js
- client-ts/Microsoft.AspNetCore.SignalR.Test.Server/wwwroot/js/webSocketTests.js
Makes long polling work on IE10 and IE9
Fixes: #845
> Replacing Cache-Control header with nonce

- client-ts/Microsoft.AspNetCore.SignalR.Client.TS.Tests/Connection.spec.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/Formatters.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/HttpConnection.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/HubConnection.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/IHubConnectionOptions.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/Transports.ts
- client-ts/Microsoft.AspNetCore.SignalR.Test.Server/wwwroot/js/common.js
- client-ts/Microsoft.AspNetCore.SignalR.Test.Server/wwwroot/js/connectionTests.js
- client-ts/Microsoft.AspNetCore.SignalR.Test.Server/wwwroot/js/hubConnectionTests.js
- client-ts/Microsoft.AspNetCore.SignalR.Test.Server/wwwroot/js/webSocketTests.js
The tests are failing on this single thing. Once changed they pass.
> Making MsgPack work in IE10

- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/HubConnection.ts
- src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs
- src/Microsoft.AspNetCore.SignalR.Client.Core/Internal/SignalRClientLoggerExtensions.cs
- src/Microsoft.AspNetCore.SignalR.Core/HubEndPoint.cs
- src/Microsoft.AspNetCore.Sockets.Client.Http/Internal/SocketClientLoggerExtensions.cs
> Reduce C# client logging and add HubProtocol log

- test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs
- test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/Hubs.cs
- test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/Startup.cs
Adding strongly typed hub functional tests.
> Add Hub<T> Functional Tests

- client-ts/Microsoft.AspNetCore.SignalR.Client.TS.Tests/HubConnection.spec.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/HubConnection.ts
...and a possibility to remove callbacks
Fixes: #807
> Adding support for multiple callbacks per client side method

- src/Microsoft.AspNetCore.SignalR.Core/HubContext`T.cs
- src/Microsoft.AspNetCore.SignalR.Core/IHubContext`T.cs
- src/Microsoft.AspNetCore.SignalR.Core/SignalRDependencyInjectionExtensions.cs
- test/Microsoft.AspNetCore.SignalR.Tests/HubEndpointTests.cs
This is https://github.com/aspnet/SignalR/pull/783 rebased on the latest dev
> Ft winston typed hub context

- src/Microsoft.AspNetCore.SignalR.Common/Internal/Formatters/BinaryMessageParser.cs
Removed extra slice
Also removed the loop for the size test instead of just an if?
> Remove extra slice

- client-ts/Microsoft.AspNetCore.SignalR.Client.TS.Tests/Connection.spec.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS.Tests/HubConnection.spec.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/HttpConnection.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/HubConnection.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/IConnection.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/Transports.ts
- client-ts/Microsoft.AspNetCore.SignalR.Test.Server/wwwroot/js/connectionTests.js
- client-ts/Microsoft.AspNetCore.SignalR.Test.Server/wwwroot/js/hubConnectionTests.js
- samples/ChatSample/Views/Home/Index.cshtml
- samples/SocketsSample/wwwroot/hubs.html
- samples/SocketsSample/wwwroot/sockets.html
- samples/SocketsSample/wwwroot/streaming.html
> Enabling multiple callbacks for HubConnection.onClose

- src/Microsoft.AspNetCore.SignalR.Client.Core/Internal/SignalRClientLoggerExtensions.cs
- src/Microsoft.AspNetCore.SignalR.Core/Internal/SignalRCoreLoggerExtensions.cs
- src/Microsoft.AspNetCore.Sockets.Client.Http/HttpConnection.cs
- src/Microsoft.AspNetCore.Sockets.Client.Http/Internal/SocketClientLoggerExtensions.cs
- src/Microsoft.AspNetCore.Sockets.Http/Internal/SocketHttpLoggerExtensions.cs
- src/Microsoft.AspNetCore.Sockets/Internal/SocketLoggerExtensions.cs
> add names to EventIds used by logger extensions

- src/Microsoft.AspNetCore.SignalR.Core/HubEndPoint.cs
- test/Microsoft.AspNetCore.SignalR.Tests/HubEndpointTests.cs
We need to close the connection if there is an exception when writing to the transport on the server side. Currently if an exception happens it leaves the connection in an unsable state - after the exception no messages from the server will be sent to the client because the writing loop is terminated. Ignoring the message could cause hangs on the client side since we can fail while writing a completion message. In this case if the client is awaiting the invocation it will hang because the task will never be completed.
Fixes: #861 and #916
> Exceptions thrown during writing should close the connection

- src/Microsoft.AspNetCore.SignalR.Core/DefaultHubLifetimeManager.cs
- src/Microsoft.AspNetCore.SignalR.Redis/RedisHubLifetimeManager.cs
- test/Microsoft.AspNetCore.SignalR.Tests/DefaultHubLifetimeManagerTests.cs
- Added some tests for the DefaultHubLifetimeManager
#905
> Check for null before sending to a specific connection id

- src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs
- src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnectionExtensions.InvokeAsync.cs
- src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnectionExtensions.InvokeAsyncGeneric.cs
- src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnectionExtensions.SendAsync.cs
- src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnectionExtensions.StreamAsync.cs
- src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnectionExtensions.cs
- src/Microsoft.AspNetCore.SignalR.Core/IClientProxyExtensions.cs
- Added 0 arg overload for InvokeAsync
> Added overloads from 0-n arguments

- samples/ClientSample/HubSample.cs
- specs/HubProtocol.md
- src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs
- src/Microsoft.AspNetCore.SignalR.Client.Core/InvocationRequest.cs
- src/Microsoft.AspNetCore.SignalR.Common/Internal/Protocol/CancelInvocationMessage.cs
- src/Microsoft.AspNetCore.SignalR.Common/Internal/Protocol/InvocationMessage.cs
- src/Microsoft.AspNetCore.SignalR.Common/Internal/Protocol/JsonHubProtocol.cs
- src/Microsoft.AspNetCore.SignalR.Common/Internal/Protocol/MessagePackHubProtocol.cs
- src/Microsoft.AspNetCore.SignalR.Core/HubConnectionContext.cs
- src/Microsoft.AspNetCore.SignalR.Core/HubEndPoint.cs
- src/Microsoft.AspNetCore.SignalR.Core/Internal/AsyncEnumeratorAdapters.cs
- src/Microsoft.AspNetCore.SignalR.Core/Internal/SignalRCoreLoggerExtensions.cs
- src/Microsoft.AspNetCore.Sockets.Client.Http/SendUtils.cs
- test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs
- test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/Hubs.cs
- test/Microsoft.AspNetCore.SignalR.Common.Tests/Internal/Protocol/JsonHubProtocolTests.cs
- test/Microsoft.AspNetCore.SignalR.Tests/HubEndpointTests.cs
- test/Microsoft.AspNetCore.SignalR.Tests/TestClient.cs
Opening this early to get feedback on the spec mostly and to see if I'm missing anything major with the feature.
Working on adding a couple more tests and reviewing my changes.
> Adding CancelInvocation message

- client-ts/Microsoft.AspNetCore.SignalR.Client.TS.Tests/HubConnection.spec.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS.Tests/JasmineUtils.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/Observable.ts
> Optional error and complete functions for observables

- src/Microsoft.AspNetCore.SignalR.Core/HubEndPoint.cs
- src/Microsoft.AspNetCore.SignalR.Core/HubOptions.cs
- test/Microsoft.AspNetCore.SignalR.Tests/HubEndpointTests.cs
> Add negotiate timeout option to hub options

- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/Loggers.ts
Summary of the changes
- Using console specific methods for logging Error, Warning and Information messages
Addresses #802
> Improved ts client console logging

- src/Microsoft.AspNetCore.SignalR.Core/DefaultHubLifetimeManager.cs
- src/Microsoft.AspNetCore.SignalR.Core/HubGroupList.cs
This is https://github.com/aspnet/SignalR/pull/997 rebased on latest dev.
> Groups collection without lock

- samples/ClientSample/RawSample.cs
- src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs
- src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnectionExtensions.cs
- src/Microsoft.AspNetCore.SignalR.Client.Core/Internal/SignalRClientLoggerExtensions.cs
- src/Microsoft.AspNetCore.Sockets.Abstractions/IConnection.cs
- src/Microsoft.AspNetCore.Sockets.Client.Http/HttpConnection.cs
- src/Microsoft.AspNetCore.Sockets.Client.Http/HttpConnectionExtensions.cs
- src/Microsoft.AspNetCore.Sockets.Client.Http/Internal/SocketClientLoggerExtensions.cs
- test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs
- test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/Hubs.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/HttpConnectionTests.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/HubConnectionTests.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/TestConnection.cs
- test/Microsoft.AspNetCore.SignalR.Tests/EndToEndTests.cs
Removed the Receive event in favor of an OnReceived method as detailed in https://github.com/aspnet/SignalR/issues/900
Roast Me
> OnReceived

- src/Microsoft.AspNetCore.SignalR.Redis/RedisHubLifetimeManager.cs
- test/Microsoft.AspNetCore.SignalR.Redis.Tests/RedisHubLifetimeManagerTests.cs
> [Redis] Adding same group to connection multiple times should NOP

- test/Microsoft.AspNetCore.SignalR.Tests/HubEndpointTests.cs
This Task.Delay needs to be awaited
> Await a delay

- specs/TransportProtocols.md
> Http Post section revision

- src/Microsoft.AspNetCore.SignalR.Redis/Internal/RedisLoggerExtensions.cs
- src/Microsoft.AspNetCore.SignalR.Redis/RedisHubLifetimeManager.cs
- test/Microsoft.AspNetCore.SignalR.Redis.Tests/RedisHubLifetimeManagerTests.cs
- test/Microsoft.AspNetCore.SignalR.Tests/DefaultHubLifetimeManagerTests.cs
https://github.com/aspnet/SignalR/issues/1054
> Handle errors in Redis subscription callbacks

- test/Common/ServerFixture.cs
@moozzyk @ryanbrandenburg 
This should make tests pass on CI
> Use different ports in ServerFixture for testing

- build/dependencies.props
- src/Microsoft.AspNetCore.Sockets/ConnectionManager.cs
- src/Microsoft.AspNetCore.Sockets/DefaultConnectionContext.cs
- src/Microsoft.AspNetCore.Sockets/Internal/SocketEventSource.cs
- src/Microsoft.AspNetCore.Sockets/Internal/SocketLoggerExtensions.cs
- src/Microsoft.AspNetCore.Sockets/Microsoft.AspNetCore.Sockets.csproj
Part of #349 
First time Eventing, lets see how it goes
@anurse
> Adding EventSource/EventCounters to Sockets

- .appveyor.yml
- .travis.yml
- test/Common/ServerFixture.cs
- test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs
- test/Microsoft.AspNetCore.SignalR.Redis.Tests/Docker.cs
- test/Microsoft.AspNetCore.SignalR.Redis.Tests/EchoHub.cs
- test/Microsoft.AspNetCore.SignalR.Redis.Tests/Microsoft.AspNetCore.SignalR.Redis.Tests.csproj
- test/Microsoft.AspNetCore.SignalR.Redis.Tests/RedisEndToEnd.cs
- test/Microsoft.AspNetCore.SignalR.Redis.Tests/RedisServerFixture.cs
- test/Microsoft.AspNetCore.SignalR.Redis.Tests/SkipIfDockerNotPresentAttribute.cs
- test/Microsoft.AspNetCore.SignalR.Redis.Tests/Startup.cs
- test/Microsoft.AspNetCore.SignalR.Tests/EndToEndTests.cs
Recreating, wouldn't let me reopen
Requires #1037 to be in before merging.
> [Redis] Add functional test support

- test/Microsoft.AspNetCore.SignalR.Tests/MapSignalRTests.cs
@Tratcher @moozzyk 
Reacting to https://github.com/aspnet/Hosting/pull/1267
> React to delayed Configure in Hosting

- test/Microsoft.AspNetCore.SignalR.Redis.Tests/Docker.cs
- test/Microsoft.AspNetCore.SignalR.Redis.Tests/Startup.cs
Our CI was taking 5.9 seconds to download new redis images
> Give redis docker image time to download

- src/Microsoft.AspNetCore.SignalR.Common/Internal/Protocol/HubProtocolConstants.cs
@mikaelm12 on the case again ;).
Just going to merge this once the build is green confirming I didn't somehow break the build :P
> forgot a copyright header

- README.md
> Fix dotnet myget npm registry link

- src/Microsoft.AspNetCore.SignalR.Core/DynamicHubClients.cs
- src/Microsoft.AspNetCore.SignalR.Core/HubCallerClients.cs
- src/Microsoft.AspNetCore.SignalR.Core/IHubCallerClients`T.cs
- src/Microsoft.AspNetCore.SignalR.Core/TypedHubClients.cs
- test/Microsoft.AspNetCore.SignalR.Redis.Tests/RedisHubLifetimeManagerTests.cs
- test/Microsoft.AspNetCore.SignalR.Tests/HubEndpointTests.cs
The name says it all. (Now based on dev)
> Others in group

- test/Microsoft.AspNetCore.SignalR.Tests/HubEndpointTestUtils/Hubs.cs
- test/Microsoft.AspNetCore.SignalR.Tests/HubEndpointTestUtils/Utils.cs
- test/Microsoft.AspNetCore.SignalR.Tests/HubEndpointTests.cs
Cleaning up the HubEndPointTests file a little. Moving ~600 lines out of this file.
Getting the Hubs out of this file and adding a a utils class as well.
> Refactoring HubEndPointTests

- .travis.yml
- build/repo.props
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/Microsoft.AspNetCore.SignalR.Client.TS.csproj
- client-ts/package-lock.json
- client-ts/package.json
- korebuild-lock.txt
- korebuild.json
- version.props
Revert part of #https://github.com/aspnet/SignalR/pull/1172
Ensure the NPM package matches the NuGet package versions
Also, updates to support generating a bill-of-materials. Part of https://github.com/aspnet/Universe/issues/679. Example output cc @muratg 
```xml
<Build>
<Artifacts>
<Artifact Id="Microsoft.AspNetCore.SignalR.1.0.0-preview1-t000.nupkg" Type="NuGetPackage" PackageId="Microsoft.AspNetCore.SignalR" Version="1.0.0-preview1-t000" TargetFramework="netstandard2.0" CommitHash="ac236efdae300ab2fab4adcefb97494c78ba1992" FileHash="2028713EB8D51A68F2F711F277231764F012B292FA2872A3395413423FEA80CE" />
<Artifact Id="Microsoft.AspNetCore.SignalR.1.0.0-preview1-t000.symbols.nupkg" Type="NuGetSymbolsPackage" PackageId="Microsoft.AspNetCore.SignalR" Version="1.0.0-preview1-t000" …
```
> Revert package version to 1.0.0-preview1 and update build tools

- samples/ChatSample/PresenceHubLifetimeManager.cs
- src/Microsoft.AspNetCore.SignalR.Core/DefaultHubLifetimeManager.cs
- src/Microsoft.AspNetCore.SignalR.Core/DynamicHubClients.cs
- src/Microsoft.AspNetCore.SignalR.Core/HubCallerClients.cs
- src/Microsoft.AspNetCore.SignalR.Core/HubContext.cs
- src/Microsoft.AspNetCore.SignalR.Core/HubContext`T.cs
- src/Microsoft.AspNetCore.SignalR.Core/HubLifetimeManager.cs
- src/Microsoft.AspNetCore.SignalR.Core/IHubClients`T.cs
- src/Microsoft.AspNetCore.SignalR.Core/Proxies.cs
- src/Microsoft.AspNetCore.SignalR.Core/TypedHubClients.cs
- src/Microsoft.AspNetCore.SignalR.Redis/RedisHubLifetimeManager.cs
- test/Microsoft.AspNetCore.SignalR.Tests/HubEndpointTestUtils/Hubs.cs
- test/Microsoft.AspNetCore.SignalR.Tests/HubEndpointTests.cs
Need suggestions with some of the naming 😄
> Invoke Multiple Connections

- samples/ChatSample/Hubs/Chat.cs
> Fix ChatSample to send array correctly

- samples/ChatSample/PresenceHubLifetimeManager.cs
- src/Microsoft.AspNetCore.SignalR.Core/DefaultHubLifetimeManager.cs
- src/Microsoft.AspNetCore.SignalR.Core/DynamicHubClients.cs
- src/Microsoft.AspNetCore.SignalR.Core/HubCallerClients.cs
- src/Microsoft.AspNetCore.SignalR.Core/HubClients.cs
- src/Microsoft.AspNetCore.SignalR.Core/HubClients`T.cs
- src/Microsoft.AspNetCore.SignalR.Core/HubLifetimeManager.cs
- src/Microsoft.AspNetCore.SignalR.Core/IHubClients`T.cs
- src/Microsoft.AspNetCore.SignalR.Core/Proxies.cs
- src/Microsoft.AspNetCore.SignalR.Core/TypedHubClients.cs
- src/Microsoft.AspNetCore.SignalR.Redis/RedisHubLifetimeManager.cs
- test/Microsoft.AspNetCore.SignalR.Tests/HubEndpointTestUtils/Hubs.cs
- test/Microsoft.AspNetCore.SignalR.Tests/HubEndpointTests.cs
Part of https://github.com/aspnet/SignalR/issues/734
> Invoke Multiple Groups

- samples/ChatSample/PresenceHubLifetimeManager.cs
- src/Microsoft.AspNetCore.SignalR.Core/DefaultHubLifetimeManager.cs
- src/Microsoft.AspNetCore.SignalR.Core/DynamicHubClients.cs
- src/Microsoft.AspNetCore.SignalR.Core/HubCallerClients.cs
- src/Microsoft.AspNetCore.SignalR.Core/HubClients.cs
- src/Microsoft.AspNetCore.SignalR.Core/HubClients`T.cs
- src/Microsoft.AspNetCore.SignalR.Core/HubLifetimeManager.cs
- src/Microsoft.AspNetCore.SignalR.Core/IHubClients`T.cs
- src/Microsoft.AspNetCore.SignalR.Core/Proxies.cs
- src/Microsoft.AspNetCore.SignalR.Core/TypedHubClients.cs
- src/Microsoft.AspNetCore.SignalR.Redis/RedisHubLifetimeManager.cs
- test/Microsoft.AspNetCore.SignalR.Tests/HubEndpointTestUtils/Hubs.cs
- test/Microsoft.AspNetCore.SignalR.Tests/HubEndpointTests.cs
> Invoke Multiple Users

- samples/SocketsSample/Hubs/Chat.cs
- samples/SocketsSample/Hubs/DynamicChat.cs
- samples/SocketsSample/Hubs/HubTChat.cs
- samples/SocketsSample/wwwroot/hubs.html
Updating SocketsSample with new IHubClients and IHubCallerClients APIs
There was some missing functionality that we can now add easily.
> Updating SocketsSample

- samples/SocketsSample/Hubs/Chat.cs
- samples/SocketsSample/wwwroot/hubs.html
Send to Individual Connections
> SocketsSample Send to Connection

- client-ts/Microsoft.AspNetCore.SignalR.Client.TS.Tests/HubConnection.spec.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/HubConnection.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/IHubProtocol.ts
- client-ts/Microsoft.AspNetCore.SignalR.Client.TS/Observable.ts
https://github.com/aspnet/SignalR/issues/898
> Support stream cancellation on TS client

- src/Microsoft.AspNetCore.SignalR.Client.Core/Internal/SignalRClientLoggerExtensions.cs
- src/Microsoft.AspNetCore.SignalR.Core/Internal/SignalRCoreLoggerExtensions.cs
- src/Microsoft.AspNetCore.SignalR.Redis/Internal/RedisLoggerExtensions.cs
- src/Microsoft.AspNetCore.Sockets.Client.Http/Internal/SocketClientLoggerExtensions.cs
- src/Microsoft.AspNetCore.Sockets.Http/Internal/SocketHttpLoggerExtensions.cs
- src/Microsoft.AspNetCore.Sockets/Internal/SocketLoggerExtensions.cs
First part of https://github.com/aspnet/SignalR/issues/1169
> EventId starts at 1 for logging

- benchmarks/Microsoft.AspNetCore.SignalR.Microbenchmarks/BroadcastBenchmark.cs
- client-ts/Microsoft.AspNetCore.SignalR.Test.Server/TestHub.cs
- samples/ChatSample/Hubs/Chat.cs
- samples/ChatSample/PresenceHubLifetimeManager.cs
- samples/JwtSample/Broadcaster.cs
- samples/SocketsSample/Hubs/Chat.cs
- src/Microsoft.AspNetCore.SignalR.Core/DefaultHubLifetimeManager.cs
- src/Microsoft.AspNetCore.SignalR.Core/DynamicClientProxy.cs
- src/Microsoft.AspNetCore.SignalR.Core/HubLifetimeManager.cs
- src/Microsoft.AspNetCore.SignalR.Core/IClientProxy.cs
- src/Microsoft.AspNetCore.SignalR.Core/IClientProxyExtensions.cs
- src/Microsoft.AspNetCore.SignalR.Core/Proxies.cs
- src/Microsoft.AspNetCore.SignalR.Core/TypedClientBuilder.cs
- src/Microsoft.AspNetCore.SignalR.Redis/RedisHubLifetimeManager.cs
- test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/Hubs.cs
- test/Microsoft.AspNetCore.SignalR.Redis.Tests/EchoHub.cs
- test/Microsoft.AspNetCore.SignalR.Redis.Tests/RedisHubLifetimeManagerTests.cs
- test/Microsoft.AspNetCore.SignalR.Tests/DefaultHubLifetimeManagerTests.cs
- test/Microsoft.AspNetCore.SignalR.Tests/HubEndpointTestUtils/Hubs.cs
- test/Microsoft.AspNetCore.SignalR.Tests/HubEndpointTests.cs
> Rename InvokeAsync to SendAsync on the server

- src/Microsoft.AspNetCore.SignalR.Core/HubConnectionContext.cs
- src/Microsoft.AspNetCore.Sockets.Http/HttpConnectionDispatcher.cs
- test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs
- test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/Hubs.cs
- test/Microsoft.AspNetCore.SignalR.Tests.Utils/ServerFixture.cs
Same as: https://github.com/aspnet/SignalR/pull/1322
Going through the Pranav steps
> Expose IHttpConnectionFeature properties

- README.md
- src/Microsoft.AspNetCore.SignalR.Core/HubConnectionContext.cs
- src/Microsoft.AspNetCore.Sockets.Http/HttpConnectionDispatcher.cs
- test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs
- test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/Hubs.cs
- test/Microsoft.AspNetCore.SignalR.Tests.Utils/ServerFixture.cs
Bringing this over from the release/2.1 branch
> Expose IHttpConnectionFeature properties (#1338)

- src/Microsoft.AspNetCore.SignalR.Core/HubEndPoint.cs
- test/Microsoft.AspNetCore.SignalR.Tests/HubEndpointTestUtils/Hubs.cs
- test/Microsoft.AspNetCore.SignalR.Tests/HubEndpointTests.cs
- test/Microsoft.AspNetCore.SignalR.Tests/Microsoft.AspNetCore.SignalR.Tests.csproj
* Return correct error to client from failing stream method
> Return stream method error to client (#1331)

- .appveyor.yml
- .travis.yml
> Enable 'release/' branches on Travis and AppVeyor (#1349)

- README.md
> Add note about using latest tsc version to README

- test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs
> Skip Flaky tests

- test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs
@BrennanConroy Added some logging and other fixes so we want to see the results on TeamCity
> Unskip tests

- samples/SocketsSample/wwwroot/hubs.html
https://github.com/aspnet/SignalR/pull/1247 was languishing in oblivion and getting stale so I rebased it and verified it locally. All looks good. Submitting this new PR to merge the rebased version in. I verified the sample has the desired behavior (buttons are disabled until connected, then enabled, then disabled again when disconnected).
Thanks @jackjwilliams for the contribution! Apologies it took this long to get it in :)
> Update SocketsSample html buttons based on connectivity status

- src/Microsoft.AspNetCore.SignalR.Redis/RedisHubLifetimeManager.cs
Changed wrong message type used during deserialization in "SubscribeToUser"
> Fixed exception during deserialization of a message with Redis

- README.md
See https://github.com/aspnet/SignalR/issues/1458
> Add note about required NPM version

- client-ts/FunctionalTests/FunctionalTests.csproj
- client-ts/FunctionalTests/package-lock.json
- client-ts/FunctionalTests/package.json
- client-ts/FunctionalTests/run-tests.js
- client-ts/FunctionalTests/run-tests.ts
- client-ts/FunctionalTests/run-tests.tsconfig.json
- client-ts/FunctionalTests/ts/HubConnectionTests.ts
- client-ts/FunctionalTests/ts/Utils.ts
- client-ts/FunctionalTests/ts/WebDriverReporter.ts
- client-ts/FunctionalTests/ts/index.ts
- client-ts/FunctionalTests/tsconfig.json
- client-ts/FunctionalTests/wwwroot/default.html
- client-ts/signalr-protocol-msgpack/package-lock.json
- client-ts/signalr/package-lock.json
This PR configures the `npm test` command in the `client-ts\FunctionalTests` to automatically launch a browser (headless chrome, by default) and run the functional tests, collecting the results and writing them out.
There are a few elements to this:
* We register a Jasmine Reporter in the Functional Tests that generates [Test-Anywhere Protocol (TAP)](https://testanything.org/tap-version-13-specification.html) output describing the test run as `<li>` elements in a hidden `<ul>` element (optionally made visible by the `displayTap` query string value)
* The `run-tests.js` script, uses the [`selenium-webdriver`](https://seleniumhq.github.io/selenium/docs/api/javascript/index.html) package. It:
1. Launches Selenium WebDriver
2. Launches the server
3. Instructs WebDriver to open the page on the …
> Make it possible to run the Browser Functional Tests from the command line

- src/Microsoft.AspNetCore.Sockets.Client.Http/ServerSentEventsTransport.cs
I'm so sorry @davidfowl I think rebasing and stuff messed it up
> Somehow the token didn't get passed into the reader

- src/Microsoft.AspNetCore.Sockets.Http/Internal/Transports/LongPollingTransport.cs
> Pass the array segment offset to WriteAsync

- src/Microsoft.AspNetCore.SignalR.Core/HubConnectionContext.cs
Just made the PR for a free CI run.
> Added try finally to semaphore release

- test/Microsoft.AspNetCore.SignalR.Tests.Utils/TaskExtensions.cs
- test/Microsoft.AspNetCore.SignalR.Tests/EndToEndTests.cs
> Revert "Add timeout back to hanging test"

- test/Microsoft.AspNetCore.SignalR.Tests/EndToEndTests.cs
Revert this when #1485 is done.
> Skip ConnectionCanSendAndReceiveMessages

- src/Microsoft.AspNetCore.Sockets.Http/HttpConnectionDispatcher.cs
- src/Microsoft.AspNetCore.Sockets.Http/HttpSocketOptions.cs
- src/Microsoft.AspNetCore.Sockets/ConnectionManager.cs
- test/Microsoft.AspNetCore.SignalR.Tests.Utils/PipeReaderExtensions.cs
- test/Microsoft.AspNetCore.Sockets.Tests/HttpConnectionDispatcherTests.cs
Exposing pipe thresholds in HttpSocketOptions
Issue : https://github.com/aspnet/SignalR/issues/1207
> Expose PauseWriter and ResumeWriter Thresholds

- src/Microsoft.AspNetCore.Sockets.Http/HttpConnectionDispatcher.cs
Looks like we didn't remove this.
> Removing remnants from the days of OPTIONS

- build/dependencies.props
- build/sources.props
- client-ts/FunctionalTests/EchoEndPoint.cs
- samples/SocialWeather/SocialWeatherEndPoint.cs
- samples/SocketsSample/EndPoints/MessagesEndPoint.cs
- src/Common/StreamExtensions.cs
- src/Common/WebSocketExtensions.cs
- src/Microsoft.AspNetCore.SignalR.Common/Internal/HubProtocolReaderWriter.cs
- src/Microsoft.AspNetCore.SignalR.Common/Internal/Protocol/NegotiationProtocol.cs
- src/Microsoft.AspNetCore.SignalR.Common/Microsoft.AspNetCore.SignalR.Common.csproj
- src/Microsoft.AspNetCore.Sockets.Client.Http/HttpConnection.cs
- src/Microsoft.AspNetCore.Sockets.Client.Http/Internal/StreamExtensions.cs
- src/Microsoft.AspNetCore.Sockets.Client.Http/SendUtils.cs
- src/Microsoft.AspNetCore.Sockets.Client.Http/ServerSentEventsMessageParser.cs
- src/Microsoft.AspNetCore.Sockets.Client.Http/ServerSentEventsTransport.cs
- src/Microsoft.AspNetCore.Sockets.Client.Http/WebSocketsTransport.cs
- src/Microsoft.AspNetCore.Sockets.Http/Internal/Transports/ServerSentEventsMessageFormatter.cs
- src/Microsoft.AspNetCore.Sockets.Http/Internal/Transports/WebSocketsTransport.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/ServerSentEventsParserTests.cs
- test/Microsoft.AspNetCore.SignalR.Tests.Utils/TaskExtensions.cs
- test/Microsoft.AspNetCore.SignalR.Tests/EchoEndPoint.cs
- test/Microsoft.AspNetCore.SignalR.Tests/WebSocketsTransportTests.cs
- test/Microsoft.AspNetCore.Sockets.Tests/HttpConnectionDispatcherTests.cs
- test/Microsoft.AspNetCore.Sockets.Tests/WebSocketsTests.cs
> Pipelines in corefx

- client-ts/FunctionalTests/ts/HubConnectionTests.ts
- src/Microsoft.AspNetCore.SignalR.Core/Internal/DefaultHubDispatcher.cs
- test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs
- test/Microsoft.AspNetCore.SignalR.Tests/HubEndpointTests.cs
I've included the method name to keep it consistent with the existing unauthorized error message
https://github.com/aspnet/SignalR/blob/6a2d41cc9ffc6e64af6a3dbc6d3cd0ed2bc44f52/src/Microsoft.AspNetCore.SignalR.Core/Internal/DefaultHubDispatcher.cs#L160-L166
> Improve unexpected server error message to client

- build/dependencies.props
- client-ts/rollup-base.js
- client-ts/signalr/README.md
Updating dev with changes from `release/2.1`
> Merge release/2.1 into dev.

- samples/SocketsSample/Startup.cs
- src/Microsoft.AspNetCore.SignalR.Core/HubConnectionContext.cs
- src/Microsoft.AspNetCore.SignalR.Core/HubEndPoint.cs
- src/Microsoft.AspNetCore.SignalR.Core/HubOptions.cs
- src/Microsoft.AspNetCore.SignalR.Core/HubOptionsSetup.cs
- src/Microsoft.AspNetCore.SignalR.Core/HubOptionsSetup`T.cs
- src/Microsoft.AspNetCore.SignalR.Core/HubOptions`T.cs
- src/Microsoft.AspNetCore.SignalR.Core/Internal/DefaultHubProtocolResolver.cs
- src/Microsoft.AspNetCore.SignalR.Core/Internal/IHubProtocolResolver.cs
- src/Microsoft.AspNetCore.SignalR/HubOptionsDependencyInjectionExtensions.cs
- src/Microsoft.AspNetCore.SignalR/SignalRDependencyInjectionExtensions.cs
- test/Microsoft.AspNetCore.SignalR.Tests/HubEndpointTests.cs
- test/Microsoft.AspNetCore.SignalR.Tests/Internal/DefaultHubProtocolResolverTests.cs
Adding the ability to restrict the HubProtocol on the server
Issue: https://github.com/aspnet/SignalR/issues/854
> Restrict HubProtocol on Server + HubOptions<THub>

- src/Microsoft.AspNetCore.SignalR.Core/Internal/DefaultHubDispatcher.cs
- test/Microsoft.AspNetCore.SignalR.Tests/HubEndpointTestUtils/Hubs.cs
- test/Microsoft.AspNetCore.SignalR.Tests/HubEndpointTests.cs
Fixes https://github.com/aspnet/SignalR/issues/1534
> Fix streaming hub methods combined with async

- src/Microsoft.AspNetCore.Sockets.Client.Http/Constants.cs
- src/Microsoft.AspNetCore.Sockets.Client.Http/WebSocketsTransport.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/LongPollingTransportTests.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/ServerSentEventsTransportTests.cs
- test/Microsoft.AspNetCore.SignalR.Tests/EchoEndPoint.cs
- test/Microsoft.AspNetCore.SignalR.Tests/HttpHeaderEndPoint.cs
- test/Microsoft.AspNetCore.SignalR.Tests/Startup.cs
- test/Microsoft.AspNetCore.SignalR.Tests/WebSocketsTransportTests.cs
Fixes https://github.com/aspnet/SignalR/issues/763
> Client sends user agent with version based on assembly version

- test/Microsoft.AspNetCore.SignalR.Tests/HttpHeaderEndPoint.cs
> Add File Header

- benchmarks/Microsoft.AspNetCore.SignalR.Microbenchmarks/DefaultHubDispatcherBenchmark.cs
- benchmarks/Microsoft.AspNetCore.SignalR.Microbenchmarks/Microsoft.AspNetCore.SignalR.Microbenchmarks.csproj
- src/Microsoft.AspNetCore.SignalR.Core/Internal/AsyncEnumeratorAdapters.cs
- src/Microsoft.AspNetCore.SignalR.Core/Internal/DefaultHubDispatcher.cs
- src/Microsoft.AspNetCore.SignalR.Core/Internal/HubMethodDescriptor.cs
Benchmarks in preparation for caching invocation reflection
> Hub method reflection caching and invocation benchmarks

- src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs
- src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnectionExtensions.StreamAsync.cs
- src/Microsoft.AspNetCore.SignalR.Client.Core/InvocationRequest.cs
- test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/HubConnectionProtocolTests.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/HubConnectionTests.cs
> Rename StreamAsync to StreamAsChannelAsync

- build/dependencies.props
- client-ts/FunctionalTests/TestHub.cs
- samples/SocialWeather/PersistentConnectionLifeTimeManager.cs
- samples/SocialWeather/SocialWeatherEndPoint.cs
- samples/SocketsSample/EndPoints/MessagesEndPoint.cs
- src/Microsoft.AspNetCore.SignalR.Core/HubConnectionContext.cs
- src/Microsoft.AspNetCore.Sockets.Abstractions/DefaultConnectionContext.cs
- src/Microsoft.AspNetCore.Sockets.Http/HttpConnectionDispatcher.cs
- test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/Hubs.cs
- test/Microsoft.AspNetCore.SignalR.Tests.Utils/TestClient.cs
- test/Microsoft.AspNetCore.SignalR.Tests/HubEndpointTestUtils/Hubs.cs
- test/Microsoft.AspNetCore.Sockets.Tests/HttpConnectionDispatcherTests.cs
Reacting to https://github.com/aspnet/KestrelHttpServer/pull/2395
> ConnectionMetadata is now ConnectionItems

- samples/ChatSample/HubWithPresence.cs
- samples/ChatSample/Hubs/Chat.cs
- src/Microsoft.AspNetCore.SignalR.Core/DefaultHubLifetimeManager.cs
- src/Microsoft.AspNetCore.SignalR.Core/DynamicClientProxy.cs
- src/Microsoft.AspNetCore.SignalR.Core/HubClients.cs
- src/Microsoft.AspNetCore.SignalR.Core/HubClients`T.cs
- src/Microsoft.AspNetCore.SignalR.Core/HubLifetimeManager.cs
- src/Microsoft.AspNetCore.SignalR.Core/IClientProxy.cs
- src/Microsoft.AspNetCore.SignalR.Core/IClientProxyExtensions.cs
- src/Microsoft.AspNetCore.SignalR.Core/Proxies.cs
- src/Microsoft.AspNetCore.SignalR.Core/TypedClientBuilder.cs
- src/Microsoft.AspNetCore.SignalR.Redis/RedisHubLifetimeManager.cs
- test/Microsoft.AspNetCore.SignalR.Tests/ClientProxyTests.cs
https://github.com/aspnet/SignalR/issues/1268
> Removed params from proxy's SendAsync

- src/Microsoft.AspNetCore.SignalR.Common/Internal/Formatters/BinaryMessageParser.cs
- src/Microsoft.AspNetCore.SignalR.Common/Internal/Formatters/TextMessageParser.cs
https://github.com/aspnet/SignalR/issues/1129
I'll run micro and macro tomorrow. Don't expect anything from macro until they're more stable though
> Perf in MessageParsers

- src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.Log.cs
- src/Microsoft.AspNetCore.SignalR.Client.Core/InvocationRequest.cs
- src/Microsoft.AspNetCore.SignalR.Core/HubConnectionContext.cs
- src/Microsoft.AspNetCore.SignalR.Core/HubEndPoint.cs
- src/Microsoft.AspNetCore.SignalR.Core/Internal/DefaultHubDispatcher.Log.cs
- src/Microsoft.AspNetCore.SignalR.Redis/Internal/RedisLoggerExtensions.cs
- src/Microsoft.AspNetCore.Sockets.Client.Http/HttpConnection.Log.cs
- src/Microsoft.AspNetCore.Sockets.Client.Http/LongPollingTransport.Log.cs
- src/Microsoft.AspNetCore.Sockets.Client.Http/SendUtils.cs
- src/Microsoft.AspNetCore.Sockets.Client.Http/ServerSentEventsTransport.Log.cs
- src/Microsoft.AspNetCore.Sockets.Client.Http/WebSocketsTransport.Log.cs
- src/Microsoft.AspNetCore.Sockets.Http/HttpConnectionDispatcher.Log.cs
- src/Microsoft.AspNetCore.Sockets.Http/Internal/SocketLoggerExtensions.cs
- src/Microsoft.AspNetCore.Sockets.Http/Internal/Transports/LongPollingTransport.cs
- src/Microsoft.AspNetCore.Sockets.Http/Internal/Transports/ServerSentEventsTransport.cs
- src/Microsoft.AspNetCore.Sockets.Http/Internal/Transports/WebSocketsTransport.Log.cs
> Pascal case formatted log parameter names

- benchmarks/Microsoft.AspNetCore.SignalR.Microbenchmarks/BroadcastBenchmark.cs
- benchmarks/Microsoft.AspNetCore.SignalR.Microbenchmarks/DefaultHubDispatcherBenchmark.cs
- src/Microsoft.AspNetCore.SignalR.Core/DefaultHubLifetimeManager.cs
- src/Microsoft.AspNetCore.SignalR.Redis/Internal/RedisLoggerExtensions.cs
- src/Microsoft.AspNetCore.SignalR.Redis/RedisHubLifetimeManager.cs
- test/Microsoft.AspNetCore.SignalR.Redis.Tests/RedisHubLifetimeManagerTests.cs
- test/Microsoft.AspNetCore.SignalR.Tests/DefaultHubLifetimeManagerTests.cs
> Ignore writeasync failures when sending to multiple connections

- build/dependencies.props
* Should fix race condition which occasionally causes tests to fail (https://github.com/Microsoft/vstest/issues/1435)
> Upgrade Microsoft.NET.Test.Sdk to 15.6.1

- src/Microsoft.AspNetCore.SignalR.Common/Internal/Protocol/JsonHubProtocol.cs
> Revert "The payload property was never used"

- client-ts/signalr/src/HttpClient.ts
- client-ts/signalr/src/Transports.ts
- samples/SocketsSample/Startup.cs
> Fix CORS on TS Client

- test/Microsoft.AspNetCore.SignalR.Redis.Tests/Docker.cs
> Properly wait for process exit for docker helper and log errors

- client-ts/signalr/spec/HttpConnection.spec.ts
- client-ts/signalr/src/HttpConnection.ts
- src/Microsoft.AspNetCore.Sockets.Client.Http/HttpConnection.Log.cs
- src/Microsoft.AspNetCore.Sockets.Client.Http/HttpConnection.cs
- src/Microsoft.AspNetCore.Sockets.Http/HttpConnectionDispatcher.cs
- src/Microsoft.AspNetCore.Sockets.Http/Internal/Transports/WebSocketsTransport.cs
- test/Microsoft.AspNetCore.Sockets.Tests/HttpConnectionDispatcherTests.cs
https://github.com/aspnet/SignalR/issues/1317
> Detect availability of web sockets on client and server

- client-ts/signalr/spec/HttpConnection.spec.ts
- client-ts/signalr/src/HttpConnection.ts
- src/Microsoft.AspNetCore.SignalR.Protocols.MsgPack/Internal/Protocol/MessagePackHubProtocol.cs
- src/Microsoft.AspNetCore.Sockets.Client.Http/HttpConnection.Log.cs
- src/Microsoft.AspNetCore.Sockets.Client.Http/HttpConnection.cs
- src/Microsoft.AspNetCore.Sockets.Client.Http/ServerSentEventsTransport.cs
- src/Microsoft.AspNetCore.Sockets.Http/HttpConnectionDispatcher.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/HttpConnectionTests.ConnectionLifecycle.cs
- test/Microsoft.AspNetCore.Sockets.Tests/HttpConnectionDispatcherTests.cs
> Merge Release/2.1 

- test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs
- test/Microsoft.AspNetCore.SignalR.Tests.Utils/WebSocketsSkipConditionAttribute.cs
- test/Microsoft.AspNetCore.SignalR.Tests.Utils/WebSocketsSupportedConditionAttribute.cs
- test/Microsoft.AspNetCore.SignalR.Tests/DefaultTransportFactoryTests.cs
- test/Microsoft.AspNetCore.SignalR.Tests/EndToEndTests.cs
- test/Microsoft.AspNetCore.SignalR.Tests/WebSocketsTransportTests.cs
- test/Microsoft.AspNetCore.Sockets.Tests/MapConnectionHandlerTests.cs
https://github.com/aspnet/SignalR/issues/1568
> Add conditional test attribute for WebSockets

- benchmarks/Microsoft.AspNetCore.SignalR.Microbenchmarks/Microsoft.AspNetCore.SignalR.Microbenchmarks.csproj
- Spoiler alert, it's much faster for the ones I ran at least
> Run benchmarks on .NET Core 2.1

- clients/ts/signalr/src/Transports.ts
- src/Microsoft.AspNetCore.Sockets.Client.Http/HttpConnection.cs
- src/Microsoft.AspNetCore.Sockets.Client.Http/Internal/LoggingHttpMessageHandler.cs
- src/Microsoft.AspNetCore.Sockets.Client.Http/WebSocketsTransport.Log.cs
- src/Microsoft.AspNetCore.Sockets.Client.Http/WebSocketsTransport.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/HttpConnectionTests.cs
https://github.com/aspnet/SignalR/issues/1391
> Added logging of .NET client HTTP requests

- clients/ts/FunctionalTests/ts/HubConnectionTests.ts
- clients/ts/signalr/spec/HttpConnection.spec.ts
- clients/ts/signalr/src/HttpConnection.ts
> Fallback for TS client

- src/Microsoft.AspNetCore.SignalR.Common/Internal/Protocol/HandshakeProtocol.cs
- src/Microsoft.AspNetCore.SignalR.Common/Internal/Protocol/JsonHubProtocol.cs
- src/Microsoft.AspNetCore.SignalR.Common/Internal/Protocol/JsonUtils.cs
- Use it in the HandshakeProtocol
> Use more pooled Utf8BufferTextReaders

- benchmarks/Microsoft.AspNetCore.SignalR.Microbenchmarks/Microsoft.AspNetCore.SignalR.Microbenchmarks.csproj
- build/dependencies.props
- src/Common/DuplexPipe.cs
- src/Microsoft.AspNetCore.Sockets.Client.Http/Microsoft.AspNetCore.Sockets.Client.Http.csproj
- src/Microsoft.AspNetCore.Sockets.Http/Microsoft.AspNetCore.Sockets.Http.csproj
- test/Microsoft.AspNetCore.SignalR.Client.Tests/Microsoft.AspNetCore.SignalR.Client.Tests.csproj
- test/Microsoft.AspNetCore.SignalR.Tests.Utils/Microsoft.AspNetCore.SignalR.Tests.Utils.csproj
- test/Microsoft.AspNetCore.SignalR.Tests/Microsoft.AspNetCore.SignalR.Tests.csproj
- test/Microsoft.AspNetCore.Sockets.Tests/Microsoft.AspNetCore.Sockets.Tests.csproj
React to https://github.com/aspnet/KestrelHttpServer/pull/2428
> Internalize DuplexPipe

- src/Microsoft.AspNetCore.SignalR.Core/HubConnectionContext.cs
- src/Microsoft.AspNetCore.SignalR.Core/Internal/DefaultHubProtocolResolver.cs
- src/Microsoft.AspNetCore.SignalR.Core/Internal/IHubProtocolResolver.cs
- test/Microsoft.AspNetCore.SignalR.Tests/Internal/DefaultHubProtocolResolverTests.cs
> Remove HubConnectionContext parameter from IHubProtocolResolver

- test/Microsoft.AspNetCore.SignalR.Client.Tests/HttpConnectionTests.ConnectionLifecycle.cs
Update another Fallback test. The Websocket check was in the wrong place. 
There was also another condition that wasn't accounted for.
In the case where we want to test Falling back once and websockets aren't available we don't actually need to change anything because we can successfully change from SSE to LongPolling. I added a comment for it below.
> Fix more flaky tests

- build/dependencies.props
> Upgrade deps

- benchmarks/Microsoft.AspNetCore.SignalR.Microbenchmarks/DefaultHubDispatcherBenchmark.cs
- benchmarks/Microsoft.AspNetCore.SignalR.Microbenchmarks/HubConnectionContextBenchmark.cs
- clients/ts/FunctionalTests/ts/HubConnectionTests.ts
- src/Microsoft.AspNetCore.SignalR.Core/HubConnectionContext.cs
- src/Microsoft.AspNetCore.SignalR.Core/HubConnectionHandler.cs
- src/Microsoft.AspNetCore.SignalR.Core/HubOptions.cs
- src/Microsoft.AspNetCore.SignalR.Core/HubOptionsSetup.cs
- src/Microsoft.AspNetCore.SignalR.Core/Internal/DefaultHubDispatcher.cs
- src/Microsoft.AspNetCore.SignalR.Core/Internal/ErrorMessageHelper.cs
- test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs
- test/Microsoft.AspNetCore.SignalR.Tests/HubConnectionHandlerTests.cs
#1614
Opening now to solicit early feedback
Need to fill in the exception strings
> Add detailed error option

- test/Microsoft.AspNetCore.SignalR.Client.Tests/HttpConnectionTests.ConnectionLifecycle.cs
- test/Microsoft.AspNetCore.SignalR.Tests.Utils/TestHelpers.cs
- test/Microsoft.AspNetCore.SignalR.Tests.Utils/WebSocketsSupportedConditionAttribute.cs
- test/Microsoft.AspNetCore.SignalR.Tests/EndToEndTests.cs
Issue: https://github.com/aspnet/SignalR/issues/1629
This should fix the failures in this this functional test.
> Check for Websockets in Fallback functional tests

- src/Microsoft.AspNetCore.Sockets.Client.Http/HttpConnection.Log.cs
- src/Microsoft.AspNetCore.Sockets.Client.Http/HttpConnection.cs
- src/Microsoft.AspNetCore.Sockets.Client.Http/Internal/LongPollingTransport.cs
- src/Microsoft.AspNetCore.Sockets.Client.Http/Internal/ServerSentEventsTransport.cs
- src/Microsoft.AspNetCore.Sockets.Client.Http/Internal/WebSocketsTransport.cs
- test/Microsoft.AspNetCore.SignalR.Tests/EndToEndTests.cs
https://github.com/aspnet/SignalR/issues/1485
Testing on CI
> Re-enable ConnectionCanSendAndReceiveMessages + logging

- src/Microsoft.AspNetCore.SignalR.Common/Internal/Protocol/JsonHubProtocol.cs
- test/Microsoft.AspNetCore.SignalR.Common.Tests/Internal/Protocol/JsonHubProtocolTests.cs
https://github.com/aspnet/SignalR/issues/1346
@HaoK I have tests for serializing arguments in-order and out of order. Does this cover the two scenarios correctly? Any other tests should be added?
> Deserializing ISO formatted strings in method arguments

- clients/ts/FunctionalTests/Startup.cs
- clients/ts/FunctionalTests/ts/HubConnectionTests.ts
- src/Microsoft.AspNetCore.SignalR.Protocols.MsgPack/Internal/Protocol/MessagePackHubProtocol.cs
- test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs
- test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/Startup.cs
- test/Microsoft.AspNetCore.SignalR.Common.Tests/Internal/Protocol/MessagePackHubProtocolTests.cs
- test/Microsoft.AspNetCore.SignalR.Tests/Startup.cs
Review: `InvalidDataException` or `FormatException`?
> Detailed errors enabled for functional tests

- clients/ts/signalr/src/HttpClient.ts
> Use xhr.onreadystatechange instead of xhr.onload

- src/Microsoft.AspNetCore.Http.Connections/HttpConnectionDispatcher.cs
- src/Microsoft.AspNetCore.Http.Connections/HttpConnectionManager.cs
- test/Microsoft.AspNetCore.Http.Connections.Tests/HttpConnectionManagerTests.cs
- This fixes race condition describes https://github.com/aspnet/SignalR/issues/1817
> Remove lazily initialization of the pipes

- src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/HubConnectionTests.ConnectionLifecycle.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/HubConnectionTests.Protocol.cs
> Add Handshake timeout to C# Client

- src/Microsoft.AspNetCore.Http.Connections.Client/HttpConnection.cs
- src/Microsoft.AspNetCore.Http.Connections.Client/HttpOptions.cs
- src/Microsoft.AspNetCore.Http.Connections.Client/Internal/WebSocketsTransport.cs
- src/Microsoft.AspNetCore.SignalR.Client/HubConnectionBuilderHttpExtensions.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/HttpConnectionTests.Transport.cs
- test/Microsoft.AspNetCore.SignalR.Tests/AuthConnectionHandler.cs
- test/Microsoft.AspNetCore.SignalR.Tests/EndToEndTests.cs
- test/Microsoft.AspNetCore.SignalR.Tests/Microsoft.AspNetCore.SignalR.Tests.csproj
- test/Microsoft.AspNetCore.SignalR.Tests/Startup.cs
- test/Microsoft.AspNetCore.SignalR.Tests/WebSocketsTransportTests.cs
> Set X-Requested-With on all requests

- benchmarks/Microsoft.AspNetCore.SignalR.Microbenchmarks/BroadcastBenchmark.cs
https://github.com/aspnet/SignalR/issues/1801
> Add SendAsyncGroup to broadcast benchmarks

- clients/ts/signalr/src/HttpConnection.ts
Issue: https://github.com/aspnet/SignalR/issues/1436
Need to think about how to test this.
> Don't normalize urls that start with //

- benchmarks/Microsoft.AspNetCore.SignalR.Microbenchmarks/DefaultHubActivatorBenchmark.cs
- benchmarks/Microsoft.AspNetCore.SignalR.Microbenchmarks/HubConnectionSendBenchmark.cs
- samples/ClientSample/Tcp/TcpConnection.cs
- samples/SocialWeather/Pipe/PipeWeatherStreamFormatter.cs
- src/Microsoft.AspNetCore.Http.Connections.Client/HttpConnection.cs
- src/Microsoft.AspNetCore.Http.Connections.Common/Internal/NegotiateProtocol.cs
- src/Microsoft.AspNetCore.Http.Connections/HttpConnectionContext.cs
- src/Microsoft.AspNetCore.Http.Connections/HttpConnectionDispatcher.cs
- src/Microsoft.AspNetCore.SignalR.Common/Internal/MemoryBufferWriter.cs
- src/Microsoft.AspNetCore.SignalR.Common/Internal/Protocol/HandshakeProtocol.cs
- src/Microsoft.AspNetCore.SignalR.Common/Internal/Protocol/JsonHubProtocol.cs
- src/Microsoft.AspNetCore.SignalR.Common/Internal/Protocol/LimitArrayPoolWriteStream.cs
- src/Microsoft.AspNetCore.SignalR.Core/Internal/AsyncEnumeratorAdapters.cs
- src/Microsoft.AspNetCore.SignalR.Core/TypedClientBuilder.cs
- src/Microsoft.AspNetCore.SignalR.Redis/RedisHubLifetimeManager.cs
- test/Microsoft.AspNetCore.Http.Connections.Tests/HttpConnectionDispatcherTests.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/HubConnectionTests.Protocol.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/LongPollingTransportTests.cs
- test/Microsoft.AspNetCore.SignalR.Common.Tests/Internal/Protocol/Utf8BufferTextReaderTests.cs
- test/Microsoft.AspNetCore.SignalR.Common.Tests/Internal/Protocol/Utf8BufferTextWriterTests.cs
- test/Microsoft.AspNetCore.SignalR.Tests/HubConnectionHandlerTests.cs
- test/Microsoft.AspNetCore.SignalR.Tests/WebSocketsTransportTests.cs
ReSharper -> Use var -> Solution wide
> var all the things

- benchmarks/Microsoft.AspNetCore.SignalR.Microbenchmarks/DefaultHubDispatcherBenchmark.cs
- test/Microsoft.AspNetCore.SignalR.Tests/HubEndpointTestUtils/Hubs.cs
https://github.com/aspnet/SignalR/issues/1811
> Add streaming benchmarks

- test/Microsoft.AspNetCore.SignalR.Client.Tests/ServerSentEventsTransportTests.cs
I haven't been able to repro the original issue anymore. The SSETransport code has changed since we disabled the test.
#526
> ReEnable SSETransportStopsSendAndReceiveLoopsWhenTransportStopped

- src/Microsoft.AspNetCore.Http.Connections.Client/Internal/WebSocketsTransport.cs
- src/Microsoft.AspNetCore.Http.Connections/ConnectionsAppBuilderExtensions.cs
- src/Microsoft.AspNetCore.Http.Connections/Internal/Transports/WebSocketsTransport.cs
- test/Microsoft.AspNetCore.Http.Connections.Tests/TestWebSocketConnectionFeature.cs
#1582 
Don't have any numbers yet
> 0 byte read in WebSockets

- src/Microsoft.AspNetCore.Http.Connections.Client/HttpConnection.cs
- src/Microsoft.AspNetCore.Http.Connections.Client/Internal/AccessTokenHttpMessageHandler.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/HttpConnectionTests.Helpers.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/HttpConnectionTests.Transport.cs
https://github.com/aspnet/SignalR/issues/1857
> Fix AccessTokenFactory not being called with each request

- src/Microsoft.AspNetCore.Http.Connections/HttpConnectionDispatcher.cs
- test/Microsoft.AspNetCore.Http.Connections.Tests/HttpConnectionDispatcherTests.cs
https://github.com/aspnet/SignalR/issues/1642
I've confirmed that the test failed before the lock.
> Lock when sending data to connection

- test/Microsoft.AspNetCore.SignalR.Client.Tests/LongPollingTransportTests.cs
> Buffer messages so we get a single outgoing request

- clients/ts/signalr/src/HandshakeProtocol.ts
- clients/ts/signalr/src/HubConnection.ts
- clients/ts/signalr/src/IHubProtocol.ts
Moved the handshake protocol handling out of HubConnection
> Split HandshakeProtocol into another class

- benchmarks/Microsoft.AspNetCore.SignalR.Microbenchmarks/RedisHubLifetimeManagerBenchmark.cs
- samples/ChatSample/RedisUserTracker.cs
- src/Microsoft.AspNetCore.SignalR.Core/HubConnectionContext.cs
- src/Microsoft.AspNetCore.SignalR.Redis/RedisHubLifetimeManager.cs
- src/Microsoft.AspNetCore.SignalR.Redis/RedisOptions.cs
- test/Microsoft.AspNetCore.SignalR.Redis.Tests/RedisHubLifetimeManagerTests.cs
Issue: https://github.com/aspnet/SignalR/issues/1863
> Connect to Redis async

- src/Microsoft.AspNetCore.Http.Connections/ConnectionsAppBuilderExtensions.cs
API review task
Renaming callback to configure
> Rename Callback -> Configure in UseConnections

- src/Microsoft.AspNetCore.Http.Connections/HttpConnectionManager.Log.cs
- src/Microsoft.AspNetCore.Http.Connections/HttpConnectionManager.cs
- src/Microsoft.AspNetCore.Http.Connections/Internal/TimerAwaitable.cs
- test/Microsoft.AspNetCore.Http.Connections.Tests/HttpConnectionDispatcherTests.cs
- test/Microsoft.AspNetCore.Http.Connections.Tests/HttpConnectionManagerTests.cs
- Gets rid of locks by using an event loop
> Clean up timer code with custom awaitable

- clients/ts/FunctionalTests/ts/ConnectionTests.ts
- clients/ts/FunctionalTests/ts/HubConnectionTests.ts
- clients/ts/FunctionalTests/ts/TestLogger.ts
- clients/ts/FunctionalTests/ts/WebDriverReporter.ts
- clients/ts/FunctionalTests/ts/WebSocketTests.ts
cc @ryanbrandenburg 
Hoping to merge ASAP.
> increase jasmine timeout and add timestamps to logs

- test/Microsoft.AspNetCore.SignalR.Redis.Tests/Startup.cs
> Enable detailed errors for redis tests

- src/Microsoft.AspNetCore.Http.Connections/HttpConnectionContext.cs
https://github.com/aspnet/KestrelHttpServer/pull/2482
> React to Kestrel changes

- specs/HubProtocol.md
> Remove Binary over text sample

- test/Microsoft.AspNetCore.SignalR.Client.Tests/HttpConnectionTests.cs
Preparing for aspnet/Logging#804
> Update usage of TestSink

- src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnectionExtensions.cs
> Fix 5 param On extension method

- clients/ts/signalr/src/browser-index.ts
> polyfill UInt8Array.forEach for IE

- src/Microsoft.AspNetCore.Http.Connections/HttpConnectionContext.cs
- src/Microsoft.AspNetCore.Http.Connections/HttpConnectionDispatcher.cs
- test/Microsoft.AspNetCore.Http.Connections.Tests/HttpConnectionDispatcherTests.cs
- Wait for disposal and removal of the connection
Fixes #1990
> Fixed flaky longpolling tests

- benchmarks/Microsoft.AspNetCore.SignalR.Microbenchmarks/BroadcastBenchmark.cs
- build/dependencies.props
- samples/ChatSample/PresenceHubLifetimeManager.cs
- src/Microsoft.AspNetCore.SignalR.Core/DynamicHubClients.cs
- src/Microsoft.AspNetCore.SignalR.Core/Internal/DynamicClientProxy.cs
- src/Microsoft.AspNetCore.SignalR.Core/Internal/HubCallerClients.cs
- src/Microsoft.AspNetCore.SignalR.Core/Internal/HubClients.cs
- src/Microsoft.AspNetCore.SignalR.Core/Internal/HubClients`T.cs
- src/Microsoft.AspNetCore.SignalR.Core/Internal/HubContext.cs
- src/Microsoft.AspNetCore.SignalR.Core/Internal/HubContext`T.cs
- src/Microsoft.AspNetCore.SignalR.Core/Internal/HubGroupList.cs
- src/Microsoft.AspNetCore.SignalR.Core/Internal/HubOptionsSetup.cs
- src/Microsoft.AspNetCore.SignalR.Core/Internal/HubOptionsSetup`T.cs
- src/Microsoft.AspNetCore.SignalR.Core/Internal/SignalRBuilder.cs
- src/Microsoft.AspNetCore.SignalR/SignalRDependencyInjectionExtensions.cs
> Internalize more classes

- src/Microsoft.AspNetCore.Http.Connections.Client/Internal/AccessTokenHttpMessageHandler.cs
- src/Microsoft.AspNetCore.Http.Connections.Client/Internal/ClientPipeOptions.cs
- src/Microsoft.AspNetCore.Http.Connections.Client/Internal/ConnectionLogScope.cs
- src/Microsoft.AspNetCore.Http.Connections.Client/Internal/LoggingHttpMessageHandler.cs
- src/Microsoft.AspNetCore.Http.Connections.Client/Internal/LongPollingTransport.cs
- src/Microsoft.AspNetCore.Http.Connections.Client/Internal/ServerSentEventsTransport.cs
- src/Microsoft.AspNetCore.Http.Connections.Client/Internal/WebSocketsTransport.cs
> Internalize Microsoft.AspNetCore.Http.Connections.Client.Internal

- src/Microsoft.AspNetCore.Http.Connections/Internal/HttpConnectionContext.cs
- test/Microsoft.AspNetCore.SignalR.Tests/EndToEndTests.cs
> Lazy initialize HttpConnectionContext.Items

- src/Microsoft.AspNetCore.SignalR.Redis/Internal/RedisLog.cs
https://github.com/aspnet/SignalR/pull/2036#issuecomment-381485687
> Move RedisLog to Internal namespace

- benchmarkapps/BenchmarkServer/BenchmarkServer.csproj
> Use correct MessagePack in Benchmarks

- src/Microsoft.AspNetCore.SignalR.Core/HubConnectionContext.cs
> Expose the IHubProtocol on HubConnectionContext

- test/Microsoft.AspNetCore.SignalR.Tests.Utils/VerifiableServerLoggedTest.cs
Suppress low impact test failures from #2034 and #2069
> Global suppress low impact logging verification in tests

- clients/ts/signalr-protocol-msgpack/package.json
- clients/ts/signalr/package.json
Got missed when I underped some merge issues, I only updated the package-lock.json for some reason.
> fix package.json versions

- src/Microsoft.AspNetCore.SignalR.Core/SerializedHubMessage.cs
- test/Microsoft.AspNetCore.SignalR.Redis.Tests/RedisProtocolTests.cs
- test/Microsoft.AspNetCore.SignalR.Tests.Utils/DummyHubProtocol.cs
- test/Microsoft.AspNetCore.SignalR.Tests.Utils/SyncPoint.cs
- test/Microsoft.AspNetCore.SignalR.Tests/SerializedHubMessageTests.cs
@BrennanConroy saw some concurrency issues in the benchmarks and we found that this was the cause.
Fixes #2078
> fix #2078 by adding locking

- src/Microsoft.AspNetCore.SignalR.Core/HubConnectionHandler.cs
- src/Microsoft.AspNetCore.SignalR.Core/Internal/DefaultHubDispatcher.cs
- test/Microsoft.AspNetCore.SignalR.Tests/HubConnectionHandlerTestUtils/Hubs.cs
- test/Microsoft.AspNetCore.SignalR.Tests/HubConnectionHandlerTests.cs
https://github.com/aspnet/SignalR/issues/2084
> Run hub invocations serially

- src/Microsoft.AspNetCore.SignalR/GetHttpContextExtensions.cs
- test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HeaderUserIdProvider.cs
- test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs
- test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/Hubs.cs
- test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/Startup.cs
- test/Microsoft.AspNetCore.SignalR.Tests/HubConnectionHandlerTestUtils/Hubs.cs
- test/Microsoft.AspNetCore.SignalR.Tests/HubConnectionHandlerTests.cs
Also added some tests for `IUserIdProvider` that were missing, see comments inline.
> fix #2097 by adding GetHttpContext to HubConnectionContext

- src/Microsoft.AspNetCore.SignalR.Core/DynamicHub.cs
- src/Microsoft.AspNetCore.SignalR.Core/Hub.cs
- src/Microsoft.AspNetCore.SignalR.Core/Hub`T.cs
- test/Microsoft.AspNetCore.SignalR.Tests/DefaultHubActivatorTests.cs
https://github.com/aspnet/SignalR/issues/2107
Does this fall under API review banner? It needs to be done before release or never.
> Change Hub and friends to abstract

- test/Microsoft.AspNetCore.Http.Connections.Tests/HttpConnectionDispatcherTests.cs
- test/Microsoft.AspNetCore.Http.Connections.Tests/WebSocketsTests.cs
- test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/HttpConnectionTests.ConnectionLifecycle.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/HttpConnectionTests.Transport.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/HubConnectionTests.cs
- test/Microsoft.AspNetCore.SignalR.Redis.Tests/RedisEndToEnd.cs
- test/Microsoft.AspNetCore.SignalR.Tests.Utils/VerifiableLoggedTest.cs
- test/Microsoft.AspNetCore.SignalR.Tests.Utils/VerifiableServerLoggedTest.cs
- test/Microsoft.AspNetCore.SignalR.Tests/EndToEndTests.cs
- test/Microsoft.AspNetCore.SignalR.Tests/WebSocketsTransportTests.cs
Split this out of the other change since it wasn't relevant
> Verify Verifiable spelling

- src/Microsoft.AspNetCore.SignalR.Client/HttpConnectionFactory.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/HttpConnectionFactoryTests.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/TestHttpMessageHandler.cs
I started the test, need to actually run it and verify it :).
The fix is good though and I wanted to get the PR up.
Fixes #2134
> fix #2134 by disposing httpconnection if start fails

- src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs
- test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs
> Remove unnecessary hop

- benchmarks/Microsoft.AspNetCore.SignalR.Microbenchmarks/HubConnectionReceiveBenchmark.cs
https://github.com/aspnet/SignalR/issues/2126
> Add HubConnection receive benchmark

- src/Microsoft.AspNetCore.SignalR.Core/Internal/DefaultHubDispatcher.cs
- src/Microsoft.AspNetCore.SignalR.Core/Internal/TaskCache.cs
- Remove state machines for async tail calls
- Added fast path for auth check when there are no policies
> Remove unnecessary state machines in DefautHubDispatcher

- clients/ts/FunctionalTests/ts/HubConnectionTests.ts
- clients/ts/signalr/spec/LongPollingTransport.spec.ts
- clients/ts/signalr/src/LongPollingTransport.ts
Still thinking about how best to test the Long Polling shutdown timeout case. We don't have any test coverage here yet because of pending #2048 .
Fixes #2169
> Fix #2169 by correcting shutdown timeout

- src/Microsoft.AspNetCore.SignalR.Core/Internal/SignalRCoreMarkerService.cs
- src/Microsoft.AspNetCore.SignalR.Core/SignalRConnectionBuilderExtensions.cs
- src/Microsoft.AspNetCore.SignalR.Core/SignalRDependencyInjectionExtensions.cs
- src/Microsoft.AspNetCore.SignalR/SignalRAppBuilderExtensions.cs
- src/Microsoft.AspNetCore.SignalR/SignalRDependencyInjectionExtensions.cs
- test/Microsoft.AspNetCore.SignalR.Tests/MapSignalRTests.cs
https://github.com/aspnet/SignalR/issues/2142
> Fix not detecting marker service

- src/Microsoft.AspNetCore.Http.Connections/ConnectionsRouteBuilder.cs
- src/Microsoft.AspNetCore.Http.Connections/Internal/TimerAwaitable.cs
- src/Microsoft.AspNetCore.SignalR.Core/DynamicHubClients.cs
- src/Microsoft.AspNetCore.SignalR.Core/HubClientsExtensions.cs
- src/Microsoft.AspNetCore.SignalR.Redis/RedisDependencyInjectionExtensions.cs
- src/Microsoft.AspNetCore.SignalR/SignalRDependencyInjectionExtensions.cs
https://github.com/aspnet/SignalR/issues/2131
Waiting on approval for merge into 2.1 RTM.
> Minor API cleanup

- src/Microsoft.AspNetCore.Http.Connections.Client/HttpConnection.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/HttpConnectionTests.Negotiate.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/HttpConnectionTests.cs
https://github.com/aspnet/SignalR/issues/2148
> Fix not setting HttpConnection.ConnectionId

- clients/ts/signalr/spec/HttpConnection.spec.ts
- clients/ts/signalr/src/ITransport.ts
> fix #2171 by adding HttpTransportType.None

- src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs
https://github.com/aspnet/SignalR/issues/2135
> Port C# client perf fix to release

- benchmarkapps/BenchmarkServer/signalr.json
Adding an "EchoIdle" scenario in preparation for long running tests
> New Benchmark Scenario 

- src/Microsoft.AspNetCore.Http.Connections.Common/NegotiateProtocol.cs
- test/Microsoft.AspNetCore.Http.Connections.Tests/NegotiateProtocolTests.cs
https://github.com/aspnet/SignalR/issues/2133
> Handle null collections when writing NegotiateResponse

- src/Microsoft.AspNetCore.SignalR.Client/HubConnectionBuilderHttpExtensions.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/HubConnectionBuilderExtensionsTests.cs
Issue: https://github.com/aspnet/SignalR/issues/2219
> Use params passed into HubConnectionBuilder (#2223)

- Directory.Build.targets
- benchmarkapps/BenchmarkServer/BenchmarkServer.csproj
- benchmarkapps/Crankier/Crankier.csproj
- benchmarks/Microsoft.AspNetCore.SignalR.Microbenchmarks/Microsoft.AspNetCore.SignalR.Microbenchmarks.csproj
- build/dependencies.props
- build/repo.props
- clients/ts/FunctionalTests/FunctionalTests.csproj
- clients/ts/FunctionalTests/selenium/run-tests.ts
- samples/ClientSample/ClientSample.csproj
- samples/ClientSample/Tcp/SocketReceiver.cs
- samples/ClientSample/Tcp/SocketSender.cs
- samples/SignalRSamples/SignalRSamples.csproj
- samples/SocialWeather/SocialWeather.csproj
- samples/WebSocketSample/WebSocketSample.csproj
- src/Common/MemoryBufferWriter.cs
- src/Common/PipeWriterStream.cs
- src/Common/StreamExtensions.cs
- src/Common/Utf8BufferTextReader.cs
- src/Common/Utf8BufferTextWriter.cs
- src/Common/WebSocketExtensions.cs
- src/Microsoft.AspNetCore.Http.Connections.Client/HttpConnection.cs
- src/Microsoft.AspNetCore.Http.Connections.Client/Internal/WebSocketsTransport.cs
- src/Microsoft.AspNetCore.Http.Connections.Client/Microsoft.AspNetCore.Http.Connections.Client.csproj
- src/Microsoft.AspNetCore.Http.Connections/Internal/Transports/WebSocketsTransport.cs
- src/Microsoft.AspNetCore.Http.Connections/Microsoft.AspNetCore.Http.Connections.csproj
- src/Microsoft.AspNetCore.SignalR.Common/Microsoft.AspNetCore.SignalR.Common.csproj
- test/Directory.Build.props
- test/Microsoft.AspNetCore.SignalR.Common.Tests/Internal/Protocol/MemoryBufferWriterTests.cs
- test/Microsoft.AspNetCore.SignalR.Tests.Utils/TestHelpers.cs
> Upgrade to netcoreapp2.2 and remove netcoreapp2.0 testing

- samples/JwtClientSample/JwtClientSample.csproj
- samples/JwtSample/JwtSample.csproj
> Update Jwt to 2.2

- benchmarkapps/BenchmarkServer/Hubs/EchoHub.cs
Goes with https://github.com/aspnet/benchmarks/pull/460
> More realistic echo scenario

- test/Microsoft.AspNetCore.SignalR.Common.Tests/Internal/Protocol/Utf8BufferTextWriterTests.cs
https://github.com/aspnet/SignalR/issues/2215
> Test combining multi-byte character writes with individual chars

- src/Microsoft.AspNetCore.SignalR.Redis/Internal/AckHandler.cs
https://github.com/dotnet/corefx/issues/29664
Fixes #2262
> Use correct TaskCompletionSource ctor

- benchmarkapps/BenchmarkServer/Hubs/EchoHub.cs
See https://github.com/aspnet/benchmarks/pull/464
> NTP for benchmarking

- clients/ts/signalr/src/HubConnection.ts
- clients/ts/signalr/src/index.ts
- clients/ts/signalr/tests/HubConnection.test.ts
- src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnectionState.cs
Fixes https://github.com/aspnet/SignalR/issues/2127
> Add state to TS HubConnection

- src/Microsoft.AspNetCore.Http.Connections.Client/Internal/LongPollingTransport.cs
- src/Microsoft.AspNetCore.Http.Connections.Client/Internal/SendUtils.cs
- src/Microsoft.AspNetCore.Http.Connections.Client/Internal/ServerSentEventsTransport.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/ServerSentEventsTransportTests.cs
- test/Microsoft.AspNetCore.SignalR.Tests.Utils/ServerFixture.cs
- test/Microsoft.AspNetCore.SignalR.Tests.Utils/VerifiableServerLoggedTest.cs
Fixes https://github.com/aspnet/SignalR/issues/2034
> Fix flakey tests from SSE receiving a 404 response on stop

- test/Microsoft.AspNetCore.SignalR.Tests.Utils/Microsoft.AspNetCore.SignalR.Tests.Utils.csproj
Not the best fix but this will get the tests running again.
> Fix tests after logging change

- src/Microsoft.AspNetCore.SignalR.Protocols.Json/Protocol/JsonHubProtocol.cs
- test/Microsoft.AspNetCore.SignalR.Common.Tests/Internal/Protocol/JsonHubProtocolTests.cs
Fixes https://github.com/aspnet/SignalR/issues/2311
> Fix JsonHubProtocol error message when too many arguments

- src/Microsoft.AspNetCore.Http.Connections/Internal/HttpConnectionDispatcher.Log.cs
- src/Microsoft.AspNetCore.Http.Connections/Internal/HttpConnectionDispatcher.cs
- test/Microsoft.AspNetCore.Http.Connections.Tests/HttpConnectionDispatcherTests.cs
Fixes https://github.com/aspnet/SignalR/issues/2310
> Handle incoming HTTP requests being canceled gracefully

- src/Common/JsonUtils.cs
- src/Microsoft.AspNetCore.SignalR.Protocols.Json/Protocol/JsonHubProtocol.cs
- test/Microsoft.AspNetCore.SignalR.Common.Tests/Internal/Protocol/JsonHubProtocolTests.cs
Fixes https://github.com/aspnet/SignalR/issues/2305
> Fix losing UTC DateTimeKind on ISO8601 UTC values

- src/Microsoft.AspNetCore.SignalR.Protocols.Json/Protocol/JsonHubProtocol.cs
- test/Microsoft.AspNetCore.SignalR.Common.Tests/Internal/Protocol/JsonHubProtocolTests.cs
Fixes https://github.com/aspnet/SignalR/issues/2321
>  Fix not reading to end of argument JSON on binding error

- build/publish-apps.ps1
- build/repo.targets
- clients/ts/FunctionalTests/Startup.cs
- clients/ts/FunctionalTests/ts/Common.ts
- clients/ts/FunctionalTests/ts/HubConnectionTests.ts
- samples/SignalRSamples/Startup.cs
- test/Microsoft.AspNetCore.SignalR.Redis.Tests/SkipIfDockerNotPresentAttribute.cs
> Add infrastructure to enable automatic deployment of samples

- test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubProtocolVersionTests.cs
- test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/Hubs.cs
- test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/VersionJsonHubProtocol.cs
- test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/VersionStartup.cs
Fixes https://github.com/aspnet/SignalR/issues/2197
> End to end versioning tests

- src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/HubConnectionTests.Protocol.cs
Fixes https://github.com/aspnet/SignalR/issues/2367
> Fix flaky ClientPingsMultipleTimes test

- src/Common/JsonUtils.cs
- src/Microsoft.AspNetCore.SignalR.Protocols.Json/Protocol/JsonHubProtocol.cs
- test/Microsoft.AspNetCore.SignalR.Common.Tests/Internal/Protocol/JsonHubProtocolTests.cs
> [2.1.1] Fix losing UTC DateTimeKind on ISO8601 UTC values (#2317)

- src/Microsoft.AspNetCore.Http.Connections/Internal/HttpConnectionManager.Log.cs
- src/Microsoft.AspNetCore.Http.Connections/Internal/HttpConnectionManager.cs
- src/Microsoft.AspNetCore.Http.Connections/Internal/HttpConnectionsEventSource.cs
Fixes https://github.com/aspnet/SignalR/issues/2155
> Remove scanning connections log messages

- src/Microsoft.AspNetCore.SignalR.Protocols.Json/Protocol/JsonHubProtocol.cs
- test/Microsoft.AspNetCore.SignalR.Common.Tests/Internal/Protocol/JsonHubProtocolTests.cs
> [2.1.1] Fix not reading to end of argument JSON on binding error (#2319)

- src/Microsoft.AspNetCore.Http.Connections.Client/HttpConnection.cs
- src/Microsoft.AspNetCore.Http.Connections.Client/Internal/ConnectionLogScope.cs
- src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs
- src/Microsoft.AspNetCore.SignalR.Client.Core/Internal/ConnectionLogScope.cs
- test/Microsoft.AspNetCore.SignalR.Tests.Utils/LogSinkProvider.cs
- test/Microsoft.AspNetCore.SignalR.Tests.Utils/ServerFixture.cs
- test/Microsoft.AspNetCore.SignalR.Tests.Utils/VerifiableLoggedTest.cs
- test/Microsoft.AspNetCore.SignalR.Tests.Utils/WrappingLoggerFactory.cs
Fixes https://github.com/aspnet/SignalR/issues/2153
There is also the same logging scope in HttpConnection. Should it be removed?
> Add connection ID scope to HubConnection

- README.md
> Remove AppVeyor Badge

- src/Microsoft.AspNetCore.SignalR.Client.Core/Internal/ConnectionLogScope.cs
> Return empty string for connectionId in some cases

- clients/ts/signalr/tests/Common.ts
- clients/ts/signalr/tests/HttpConnection.test.ts
- clients/ts/signalr/tests/HubConnection.test.ts
- clients/ts/signalr/tests/HubConnectionBuilder.test.ts
- clients/ts/signalr/tests/JsonHubProtocol.test.ts
- clients/ts/signalr/tests/LongPollingTransport.test.ts
#2344
Opening PR early to get feedback on the test pattern.
Will add to other tests once we review the pattern a bit.
> Add VerifyLogger to JS tests

- clients/cpp/samples/HubConnectionSample/HubConnectionSample.vcxproj
- clients/cpp/test/signalrclient-e2e-tests/Build/VS/signalrclient-e2e-tests.vcxproj
- clients/cpp/test/signalrclienttests/Build/VS/signalrclienttests.vcxproj
Some configurations weren't getting dll's and includes correctly. Think I got them all working now.
> Fix Cpp builds

- README.md
Updating the intro video to this year's build talk
> Update README Intro Video

- clients/ts/signalr/src/ServerSentEventsTransport.ts
- clients/ts/signalr/src/WebSocketTransport.ts
- clients/ts/signalr/tests/HttpConnection.test.ts
- clients/ts/signalr/tests/ServerSentEventsTransport.test.ts
- clients/ts/signalr/tests/TestEventSource.ts
#2405 
This is just for SSE. WebSockets will be a different PR.
Pay special attention to the actual SSE transport, I changed a couple things because they were wrong
> Add JS unit tests for SSE

- clients/ts/FunctionalTests/package-lock.json
- clients/ts/FunctionalTests/ts/Common.ts
- clients/ts/FunctionalTests/wwwroot/default.html
- clients/ts/package-lock.json
- clients/ts/signalr-protocol-msgpack/package-lock.json
Functional tests were broken in the browser. Also I updated my local `npm`, so the package-lock.json exploded. (PSA: update your `npm` to avoid unexploding it)
> fix running Functional Tests in the browser

- clients/ts/signalr/tests/ServerSentEventsTransport.test.ts
- clients/ts/signalr/tests/TestWebSocket.ts
- clients/ts/signalr/tests/WebSocketTransport.test.ts
> Add JS unit tests for WebSockets

- clients/java/signalr/build.gradle
- clients/java/signalr/src/main/java/Action.java
- clients/java/signalr/src/main/java/Chat.java
- clients/java/signalr/src/main/java/DefaultJsonProtocolHandShakeMessage.java
- clients/java/signalr/src/main/java/HubConnection.java
- clients/java/signalr/src/main/java/ITransport.java
- clients/java/signalr/src/main/java/InvocationMessage.java
- clients/java/signalr/src/main/java/OnReceiveCallBack.java
- clients/java/signalr/src/main/java/WebSocketTransport.java
- clients/java/signalr/src/test/java/HubConnectionTest.java
HubConnection that can Start, Stop and Send over Websockets. There's a  working chat sample that connects to the SignalRSample chat.
Keep in mind when reviewing this that it's an initial commit for this client. I don't want to increase the feature scope at all for this commit.
If you want to build locally navigate to the `clients/java/signalr ` directory and run `.\gradlew build`
Issues: https://github.com/aspnet/SignalR/issues/2482
and : https://github.com/aspnet/SignalR/issues/2508
> Initial Java Client Commit

- test/Microsoft.AspNetCore.SignalR.Redis.Tests/Docker.cs
> Harden docker detection

- clients/ts/FunctionalTests/package-lock.json
Results of `npm audit fix` on the Functional Tests. These are **test only** dependencies. There are no changes to product dependencies here. The product dependencies have no `npm audit` warnings.
> update some packages

- clients/ts/FunctionalTests/package-lock.json
- clients/ts/FunctionalTests/package.json
- clients/ts/package-lock.json
More `npm audit` fixes, still isolated to testing code, no product dependencies.
> make audit happier

- clients/java/signalr/src/main/java/HubConnection.java
- clients/java/signalr/src/test/java/HubConnectionTest.java
Adding some testing for `HubConnection` in the Java client.
Had to add another ctor to `HubConnection` to accept a transport so I could pass in a `MockTransport`
Issue: #2540
> Adding HubConnection Tests

- clients/java/signalr/src/main/java/HubConnection.java
- clients/java/signalr/src/test/java/HubConnectionTest.java
This change is in dev but not in rel/2.2
Cherry picking this then going to merge the commit back to dev to match up the history
cc @natemcmaster
> Adding HubConnection Tests for the Java Client (release/2.2) (#2550)

- clients/java/signalr/src/main/java/Action.java
- clients/java/signalr/src/main/java/Action1.java
- clients/java/signalr/src/main/java/Action2.java
- clients/java/signalr/src/main/java/Action3.java
- clients/java/signalr/src/main/java/Action4.java
- clients/java/signalr/src/main/java/Action5.java
- clients/java/signalr/src/main/java/ActionBase.java
- clients/java/signalr/src/main/java/Chat.java
- clients/java/signalr/src/main/java/HubConnection.java
- clients/java/signalr/src/main/java/Transport.java
- clients/java/signalr/src/main/java/WebSocketTransport.java
- clients/java/signalr/src/test/java/HubConnectionTest.java
> Adding Support for On Overloads in Java Client (#2568)

- clients/java/signalr/src/main/java/WebSocketTransport.java
- clients/java/signalr/src/test/java/WebSocketTransportTest.java
> Formatting urls when using the WebSocketsTransport (#2571)

- src/Microsoft.AspNetCore.SignalR.Core/SignalRDependencyInjectionExtensions.cs
- test/Microsoft.AspNetCore.SignalR.Tests/AddSignalRTests.cs
https://github.com/aspnet/SignalR/issues/2561
Porting change from release/2.2
> [2.1.3] Update AddSignalRCore to respect user registered services (#2434)

- test/Microsoft.AspNetCore.SignalR.Tests/AddSignalRTests.cs
This PR merges commits made on release/2.2 by the following committers:
* @BrennanConroy
> [automated] Merge branch 'release/2.2' => 'master'

- build/dependencies.props
- clients/java/signalr/src/main/java/CallbackMap.java
- clients/java/signalr/src/main/java/HubConnection.java
- clients/java/signalr/src/test/java/HubConnectionTest.java
- korebuild-lock.txt
Hmm, seems  like the "Update dependencies.props" commit from the CI is also included in these changes. @natemcmaster  How should we go about merging 2.2 back into master in this case?
> Merge Support for registering multiple On handlers

- clients/java/signalr/src/main/java/HubConnection.java
- clients/java/signalr/src/main/java/HubMessage.java
- clients/java/signalr/src/main/java/HubMessageType.java
- clients/java/signalr/src/main/java/HubProtocol.java
- clients/java/signalr/src/main/java/InvocationMessage.java
- clients/java/signalr/src/main/java/JsonHubProtocol.java
- clients/java/signalr/src/main/java/PingMessage.java
- clients/java/signalr/src/test/java/JsonHubProtocolTest.java
Issue: https://github.com/aspnet/SignalR/issues/2589
I've added the `HubMessage `abstraction and Enums for the different message types.
> Add HubMessage and parse messages from the server into different message types

- clients/java/signalr/src/main/java/HubConnection.java
- clients/java/signalr/src/main/java/HubConnectionState.java
- clients/java/signalr/src/test/java/HubConnectionTest.java
> Adding HubConnection State Enum (#2627)

- clients/java/signalr/src/main/java/CallbackMap.java
- clients/java/signalr/src/main/java/HubConnection.java
- clients/java/signalr/src/test/java/HubConnectionTest.java
> Remove handlers from HubConnection (#2628)

- test/Microsoft.AspNetCore.SignalR.Tests/HubConnectionHandlerTests.cs
https://github.com/aspnet/Coherence-Signed/issues/855
> Add partial handshake test

- clients/java/signalr/src/main/java/Action6.java
- clients/java/signalr/src/main/java/Action7.java
- clients/java/signalr/src/main/java/Action8.java
- clients/java/signalr/src/main/java/HubConnection.java
- clients/java/signalr/src/test/java/HubConnectionTest.java
Issue: https://github.com/aspnet/SignalR/issues/2626
> Adding Overloads up to T8.

- .github/ISSUE_TEMPLATE.md
To hopefully re-route people who are trying to file potential security issues.
> Update issue template for security issues

- build/repo.targets
- version.props
Using the VersionSuffix variable instead of hard coding "preview1"
> Using the version suffix variable

- build/repo.targets
- clients/java/signalr/.gitignore
- clients/java/signalr/build.gradle
We're now generating .pom files. Adding it to the .gitignore file at the Java client level
> Move .pom file in gradle build task

- clients/java/signalr/src/main/java/Chat.java
- clients/java/signalr/src/main/java/ConsoleLogger.java
- clients/java/signalr/src/main/java/HubConnection.java
- clients/java/signalr/src/main/java/LogLevel.java
- clients/java/signalr/src/main/java/Logger.java
- clients/java/signalr/src/main/java/NullLogger.java
- clients/java/signalr/src/main/java/WebSocketTransport.java
- clients/java/signalr/src/test/java/WebSocketTransportTest.java
Starting to add logging on the Java client
Issue: https://github.com/aspnet/SignalR/issues/2638
> Add logging infrastructure to the Java Client

- clients/ts/signalr/src/LongPollingTransport.ts
> Increase poll timeout in TS client

- test/Microsoft.AspNetCore.SignalR.Redis.Tests/RedisServerFixture.cs
> Up Redis test log level

- clients/java/signalr/src/main/java/HubConnection.java
- clients/java/signalr/src/main/java/HubMessage.java
- clients/java/signalr/src/main/java/HubProtocol.java
Hoping to get some basic docs in for preview1.
Following the oracle outline here https://www.oracle.com/technetwork/java/javase/documentation/index-137868.html#format
Fixes https://github.com/aspnet/SignalR/issues/2677
> Adding basic javadocs

- clients/ts/signalr/src/HubConnection.ts
> Check connection state in ping Typescript client

- build/repo.targets
Going to merge when I get green builds since this is currently blocking UpdateUniverse in 2.2
> disable the gradle daemon on the CI

- src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs
- test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs
> Don't start stream if already canceled

- src/Microsoft.AspNetCore.SignalR.Core/Internal/DefaultHubDispatcher.cs
- src/Microsoft.AspNetCore.SignalR.Protocols.MessagePack/Protocol/MessagePackHubProtocol.cs
- test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs
- test/Microsoft.AspNetCore.SignalR.Tests/HubConnectionHandlerTests.cs
> Provide a better error message when invoking a non-existant hub method

- clients/ts/signalr/src/HubConnectionBuilder.ts
> Expose full implementation for configureLogging in ESM definition file

- build/repo.targets
- clients/java/signalr/build.gradle
- clients/java/signalr/settings.gradle
Issue: https://github.com/aspnet/SignalR/issues/2744
> Update Java client build scripts for Maven publishing

- build/repo.targets
- clients/java/signalr/build.gradle
- version.props
Embed the build number into the Java client packages.
> add version number to java client build

- clients/java/signalr/gradle/wrapper/gradle-wrapper.properties
Running into an issue described here: https://github.com/gradle/gradle/issues/4931
Upgrading to a version greater than or equal to 4.8 (4.9 in this case) should fix it.
> Update Gradle to 4.9

- clients/java/signalr/gradle/wrapper/gradle-wrapper.properties
> Merge release/2.2

- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/ConsoleLogger.java
Looks like: `[2018-08-09T12:13Z] [Debug] Received message of type PING`
Issue: https://github.com/aspnet/SignalR/issues/2750
> Add timestamps to log messages

- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/Chat.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/HubConnection.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/HubConnectionBuilder.java
Add HubConnectionBuilder to Java client (#2780)
> Merge rel/2.2

- THIRD-PARTY-NOTICES
Add gradle to third-party notices.
> Add gradle to 3pn

- clients/ts/signalr-protocol-msgpack/README.md
- clients/ts/signalr/README.md
> Add JS API doc link to npm packages

- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/CloseMessage.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/HubConnection.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/JsonHubProtocol.java
- clients/java/signalr/src/test/java/HubConnectionTest.java
- clients/java/signalr/src/test/java/JsonHubProtocolTest.java
Adding support for more message types. 
This is basic support for the close message.
> Adding support for Close Message

- clients/ts/FunctionalTests/package-lock.json
- clients/ts/common/package-lock.json
- clients/ts/signalr-protocol-msgpack/package-lock.json
Not sure why nobody is updating these but it changes whenever I build.
> Updated the lock files

- clients/ts/signalr/tests/AbortSignal.test.ts
- clients/ts/signalr/tests/HttpClient.test.ts
- clients/ts/signalr/tests/HttpConnection.test.ts
- clients/ts/signalr/tests/HubConnection.test.ts
- clients/ts/signalr/tests/HubConnectionBuilder.test.ts
- clients/ts/signalr/tests/JsonHubProtocol.test.ts
- clients/ts/signalr/tests/LongPollingTransport.test.ts
- clients/ts/signalr/tests/ServerSentEventsTransport.test.ts
- clients/ts/signalr/tests/TextMessageFormat.test.ts
- clients/ts/signalr/tests/Utils.ts
- clients/ts/signalr/tests/WebSocketTransport.test.ts
Attempting to help with issues like https://ci3.dot.net/job/aspnet_SignalR/job/release_2.2/job/windows-Configuration_Release_prtest/164/consoleFull
> Log unhandled exceptions to help see errors in tests

- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/Chat.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/HubConnection.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/HubException.java
- clients/java/signalr/src/test/java/HubConnectionTest.java
- clients/java/signalr/src/test/java/HubExceptionTest.java
Lets users register a callback to run when a `HubConnection` is stopped.
Issue:https://github.com/aspnet/SignalR/issues/2803
> Support for Adding OnClosed Logic

- clients/ts/signalr-protocol-msgpack/src/MessagePackHubProtocol.ts
- clients/ts/signalr-protocol-msgpack/tests/MessagePackHubProtocol.test.ts
Simpler fix than adding a new polyfill 😄
> Fix TS msgpack on IE and Ping breaking connection on server

- test/Microsoft.AspNetCore.SignalR.Client.Tests/HttpConnectionTests.ConnectionLifecycle.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/ServerSentEventsTransportTests.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/TestHttpMessageHandler.cs
Adding logging for flaky test #2832 and #2835
> Add logging to transport in tests

- src/Microsoft.AspNetCore.SignalR.Redis/Internal/RedisLog.cs
> Tweak some Redis log levels

- clients/ts/signalr/src/HttpConnection.ts
- clients/ts/signalr/tests/HttpConnection.test.ts
- src/Microsoft.AspNetCore.Http.Connections.Common/NegotiateProtocol.cs
- test/Microsoft.AspNetCore.Http.Connections.Tests/NegotiateProtocolTests.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/HttpConnectionTests.Negotiate.cs
#2728 
Wanted to get the ball rolling on this and see if anyone had a different idea of how to detect this.
I did a quick test and this did what I expected when connecting to an ASP.NET SignalR Server.
> Detect ASP.NET SignalR server connection attempt

- README.md
> fix #2853 by adding blurb to readme

- test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs
Issue: https://github.com/aspnet/SignalR/issues/2790
> Fix flaky test (#2739)

- src/Microsoft.AspNetCore.Http.Connections/Internal/HttpConnectionContext.cs
- src/Microsoft.AspNetCore.Http.Connections/Internal/HttpConnectionDispatcher.cs
https://github.com/aspnet/SignalR/issues/2714
@anurse Take over if we need this in in the next couple days.
> Backport LongPolling race to 2.1.5

- build/repo.targets
Fixes https://github.com/aspnet/Coherence-Signed/issues/1004
> Use gradle to detect java

- clients/ts/FunctionalTests/package.json
Fixes https://github.com/aspnet/Coherence-Signed/issues/917
Fixes https://github.com/aspnet/Coherence-Signed/issues/918
> add --no-restore when building functional test proj

- src/Microsoft.AspNetCore.Http.Connections/Internal/HttpConnectionManager.cs
- test/Microsoft.AspNetCore.Http.Connections.Tests/HttpConnectionManagerTests.cs
> Initialize HttpConnectionManager before registering callbacks

- test/Microsoft.AspNetCore.SignalR.Tests.Utils/ServerLogScope.cs
https://github.com/aspnet/SignalR/issues/2886
Change from 2.2 https://github.com/aspnet/SignalR/pull/2742
@muratg For 2.1
> Avoid ODE in tests with Server logging (#2742)

- version.props
When this PR merges, the release/2.2 branch is open for preview3 changes.
> Update branding to 1.1.0-preview3

- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/JsonHubProtocol.java
- clients/java/signalr/src/test/java/JsonHubProtocolTest.java
Issue: https://github.com/aspnet/SignalR/issues/2822
> Unify exceptions for unsupported message types

- clients/java/signalr/build.gradle
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/CallbackMap.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/ConsoleLogger.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/HandshakeProtocol.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/HubConnection.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/HubProtocol.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/JsonHubProtocol.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/Negotiate.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/NegotiateResponse.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/Subscription.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/WebSocketTransport.java
- clients/java/signalr/src/test/java/com/microsoft/aspnet/signalr/test/HandshakeProtocolTest.java
- clients/java/signalr/src/test/java/com/microsoft/aspnet/signalr/test/HubConnectionTest.java
- clients/java/signalr/src/test/java/com/microsoft/aspnet/signalr/test/HubExceptionTest.java
- clients/java/signalr/src/test/java/com/microsoft/aspnet/signalr/test/JsonHubProtocolTest.java
- clients/java/signalr/src/test/java/com/microsoft/aspnet/signalr/test/NegotiateResponseTest.java
- clients/java/signalr/src/test/java/com/microsoft/aspnet/signalr/test/ResolveNegotiateUrlTest.java
- clients/java/signalr/src/test/java/com/microsoft/aspnet/signalr/test/WebSocketTransportTest.java
- clients/java/signalr/src/test/java/com/microsoft/aspnet/signalr/test/WebSocketTransportUrlFormatTest.java
Updated version of: https://github.com/aspnet/SignalR/pull/2912/files
> Spotless for the Java Client

- src/Common/TimerAwaitable.cs
- src/Microsoft.AspNetCore.SignalR.Redis/Internal/AckHandler.cs
> Don't capture AsyncLocals onto Timers

- benchmarks/Microsoft.AspNetCore.SignalR.Microbenchmarks/HandshakeProtocolBenchmark.cs
- benchmarks/Microsoft.AspNetCore.SignalR.Microbenchmarks/NegotiateProtocolBenchmark.cs
Split off from https://github.com/aspnet/SignalR/pull/2734.
cc @anurse
> Add Handshake Protocol benchmarks and more Negotiate Protocol benchmark cases

- test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs
https://github.com/aspnet/SignalR/issues/2943
@muratg For shiproom
> Add expected test log exception to fix flaky test

- clients/java/signalr/build.gradle
- clients/java/signalr/src/test/java/com/microsoft/aspnet/signalr/HandshakeProtocolTest.java
- clients/java/signalr/src/test/java/com/microsoft/aspnet/signalr/HubConnectionTest.java
- clients/java/signalr/src/test/java/com/microsoft/aspnet/signalr/HubExceptionTest.java
- clients/java/signalr/src/test/java/com/microsoft/aspnet/signalr/JsonHubProtocolTest.java
- clients/java/signalr/src/test/java/com/microsoft/aspnet/signalr/NegotiateResponseTest.java
- clients/java/signalr/src/test/java/com/microsoft/aspnet/signalr/ResolveNegotiateUrlTest.java
- clients/java/signalr/src/test/java/com/microsoft/aspnet/signalr/WebSocketTransportTest.java
- clients/java/signalr/src/test/java/com/microsoft/aspnet/signalr/WebSocketTransportUrlFormatTest.java
https://github.com/aspnet/SignalR/issues/2802
> Use JUnit 5 for tests

- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/HubConnection.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/Transport.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/WebSocketTransport.java
- clients/java/signalr/src/test/java/com/microsoft/aspnet/signalr/HubConnectionTest.java
- clients/java/signalr/src/test/java/com/microsoft/aspnet/signalr/WebSocketTransportTest.java
Closed https://github.com/aspnet/SignalR/pull/2944 in favor of this.
> Java Async APIs

- src/Microsoft.AspNetCore.SignalR.Core/SignalRDependencyInjectionExtensions.cs
- src/Microsoft.AspNetCore.SignalR/SignalRDependencyInjectionExtensions.cs
- test/Microsoft.AspNetCore.SignalR.Tests/AddSignalRTests.cs
https://github.com/aspnet/SignalR/issues/2931
> Idempotentize AddSignalR

- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/CloseMessage.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/CompletionMessage.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/HubConnection.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/HubProtocol.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/InvocationMessage.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/InvocationRequest.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/JsonHubProtocol.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/StreamInvocationMessage.java
- clients/java/signalr/src/test/java/com/microsoft/aspnet/signalr/HubConnectionTest.java
- clients/java/signalr/src/test/java/com/microsoft/aspnet/signalr/JsonHubProtocolTest.java
https://github.com/aspnet/SignalR/issues/2926
> [Java] Add Invoke support

- build/dependencies.props
- src/Microsoft.AspNetCore.Http.Connections/Internal/HttpConnectionContext.cs
- src/Microsoft.AspNetCore.Http.Connections/Internal/HttpConnectionDispatcher.cs
- src/Microsoft.AspNetCore.Http.Connections/Microsoft.AspNetCore.Http.Connections.csproj
https://github.com/aspnet/SignalR/issues/2948
> Clone Windows Identity in LongPolling connections

- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/HttpConnectionOptions.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/HubConnection.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/HubConnectionBuilder.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/WebSocketTransport.java
- clients/java/signalr/src/test/java/com/microsoft/aspnet/signalr/HandshakeProtocolTest.java
- clients/java/signalr/src/test/java/com/microsoft/aspnet/signalr/HttpConnectionOptionsTest.java
- clients/java/signalr/src/test/java/com/microsoft/aspnet/signalr/HubConnectionBuilderTest.java
- clients/java/signalr/src/test/java/com/microsoft/aspnet/signalr/HubConnectionTest.java
- clients/java/signalr/src/test/java/com/microsoft/aspnet/signalr/MockTransport.java
- clients/java/signalr/src/test/java/com/microsoft/aspnet/signalr/WebSocketTransportTest.java
- clients/java/signalr/src/test/java/com/microsoft/aspnet/signalr/WebSocketTransportUrlFormatTest.java
- clients/java/signalr/src/test/java/com/microsoft/aspnet/signalr/sample/Chat.java
Changes from the `HubConnectionBuilder `API Review.  
Doing some argument validation in the HubConnectionBuilder and adding an `HttpConnectionOptions` type. Also removing some `HubConnection` constructors.
> Java Client HubConnectionBuilder API Review

- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/HubConnection.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/Negotiate.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/WebSocketTransport.java
- clients/java/signalr/src/test/java/com/microsoft/aspnet/signalr/WebSocketTransportTest.java
Still early and hacky but just want to leave this out here.Started hacking on changing the websocket library to Square's OkHttp WebSocket implementation. 
The motivation for doing this now is that we aren't keeping track of cookies which is causing problems and this library provides an easier way to do that. Still need to verify that behavior
One issue I have now is I'm a little unsure how to deal with errors during connection with these websockets. 
Issue: https://github.com/aspnet/SignalR/issues/2792
Issue: https://github.com/aspnet/SignalR/issues/3013
> Change websockets library

- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/DefaultHttpClient.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/HandshakeProtocol.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/HttpClient.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/HubConnection.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/HubConnectionBuilder.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/Negotiate.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/OkHttpWebSocketWrapper.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/Transport.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/WebSocketTransport.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/WebSocketWrapper.java
- clients/java/signalr/src/test/java/com/microsoft/aspnet/signalr/HubConnectionTest.java
- clients/java/signalr/src/test/java/com/microsoft/aspnet/signalr/TestHttpClient.java
- clients/java/signalr/src/test/java/com/microsoft/aspnet/signalr/WebSocketTransportTest.java
- clients/java/signalr/src/test/java/com/microsoft/aspnet/signalr/WebSocketTransportUrlFormatTest.java
https://github.com/aspnet/SignalR/issues/2915
Wrote a single test for proof-of-concept. Will leave more tests to a later PR, want this change to be focused on getting the HttpClient code in.
The main part to focus on is the negotiate stuff, it seems a little hacky right now.
> [Java] Add HttpClient support for testing

- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/Action.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/Action1.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/Action2.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/Action3.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/Action4.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/Action5.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/Action6.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/Action7.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/Action8.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/ActionBase.java
Interfaces with only one method should be marked `@FunctionalInterfaces`
> [Java] Functional Interfaces

- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/HubConnection.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/JsonHubProtocol.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/Transport.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/WebSocketTransport.java
- clients/java/signalr/src/test/java/com/microsoft/aspnet/signalr/HubConnectionTest.java
- clients/java/signalr/src/test/java/com/microsoft/aspnet/signalr/JsonHubProtocolTest.java
- clients/java/signalr/src/test/java/com/microsoft/aspnet/signalr/MockTransport.java
- clients/java/signalr/src/test/java/com/microsoft/aspnet/signalr/WebSocketTransportTest.java
- clients/java/signalr/src/test/java/com/microsoft/aspnet/signalr/WebSocketTransportUrlFormatTest.java
I think this finishes client re-usability.
> [Java] Pass Url to transport start so we can reuse the transport

- build/repo.targets
Should solve Issue: https://github.com/aspnet/SignalR/issues/3083
> Add Java Check

- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/CallbackMap.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/CloseMessage.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/CompletionMessage.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/DefaultHttpClient.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/HandshakeProtocol.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/HandshakeRequestMessage.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/HandshakeResponseMessage.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/HttpClient.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/HubConnection.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/HubConnectionBuilder.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/InvocationHandler.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/InvocationMessage.java
- clients/java/signalr/src/test/java/com/microsoft/aspnet/signalr/HandshakeProtocolTest.java
- clients/java/signalr/src/test/java/com/microsoft/aspnet/signalr/HubConnectionBuilderTest.java
- clients/java/signalr/src/test/java/com/microsoft/aspnet/signalr/HubConnectionTest.java
- clients/java/signalr/src/test/java/com/microsoft/aspnet/signalr/TestUtils.java
- clients/java/signalr/src/test/java/com/microsoft/aspnet/signalr/sample/Chat.java
Here are the API review changes from our meeting this week!
Thanks @JonathanGiles for the review!
> Java Client API Review pt2

- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/CallbackMap.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/CloseMessage.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/CompletionMessage.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/DefaultHttpClient.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/HandshakeProtocol.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/HandshakeRequestMessage.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/HandshakeResponseMessage.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/HttpClient.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/HubConnection.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/HubConnectionBuilder.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/InvocationHandler.java
- clients/java/signalr/src/main/java/com/microsoft/aspnet/signalr/InvocationMessage.java
- clients/java/signalr/src/test/java/com/microsoft/aspnet/signalr/HandshakeProtocolTest.java
- clients/java/signalr/src/test/java/com/microsoft/aspnet/signalr/HubConnectionBuilderTest.java
- clients/java/signalr/src/test/java/com/microsoft/aspnet/signalr/HubConnectionTest.java
- clients/java/signalr/src/test/java/com/microsoft/aspnet/signalr/TestUtils.java
- clients/java/signalr/src/test/java/com/microsoft/aspnet/signalr/sample/Chat.java
Java Client API Review pt2 (#3078)
> Merge release/2.2 

- .vscode/launch.json
- clients/java/signalr/build.gradle
- clients/java/signalr/src/main/java/com/microsoft/signalr/HttpHubConnectionBuilder.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/HubConnection.java
- clients/java/signalr/src/test/java/com/microsoft/signalr/HubConnectionTest.java
- clients/java/signalr/src/test/java/com/microsoft/signalr/sample/Chat.java
Part of https://github.com/aspnet/SignalR/issues/3073
> [Java] Make public API look like RxJava

- version.props
Changing from 0.1.0 to 1.0.0 👍 
Issue: https://github.com/aspnet/SignalR/issues/3002
> Upgrade to RTM versioning in the Java client

- clients/java/signalr/src/main/java/com/microsoft/signalr/HttpHubConnectionBuilder.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/HubConnection.java
- clients/java/signalr/src/test/java/com/microsoft/signalr/HandshakeProtocolTest.java
- clients/java/signalr/src/test/java/com/microsoft/signalr/HubConnectionTest.java
- clients/java/signalr/src/test/java/com/microsoft/signalr/MockTransport.java
- clients/java/signalr/src/test/java/com/microsoft/signalr/TestUtils.java
New pr for this.
With a timeout longer than the `DefaultHandshakeTimeout` on the server.
Issue: https://github.com/aspnet/SignalR/issues/2903
> Wait for handshake response

- clients/java/signalr/src/main/java/com/microsoft/signalr/HubConnection.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/PingMessage.java
- clients/java/signalr/src/test/java/com/microsoft/signalr/HubConnectionTest.java
- clients/java/signalr/src/test/java/com/microsoft/signalr/MockTransport.java
https://github.com/aspnet/SignalR/issues/3025
> [Java] Add pings and server timeout

- clients/java/signalr/src/main/java/com/microsoft/signalr/CallbackMap.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/DefaultHttpClient.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/HandshakeProtocol.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/HttpHubConnectionBuilder.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/HubConnection.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/HubConnectionBuilder.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/HubException.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/InvocationHandler.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/InvocationRequest.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/PingMessage.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/StreamInvocationMessage.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/Subscription.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/TransferFormat.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/WebSocketTransport.java
`withHandshakeResponseTimeout` wasn't public and `TransferFormat` was public
> [Java] Fix incorrect visibility and some minor cleanup

- clients/java/signalr/src/main/java/com/microsoft/signalr/HubConnection.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/HubException.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/HubProtocol.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/InvocationBinder.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/JsonHubProtocol.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/NegotiateResponse.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/OnReceiveCallBack.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/Transport.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/WebSocketTransport.java
- clients/java/signalr/src/test/java/com/microsoft/signalr/HubConnectionTest.java
- clients/java/signalr/src/test/java/com/microsoft/signalr/JsonHubProtocolTest.java
- clients/java/signalr/src/test/java/com/microsoft/signalr/MockTransport.java
- clients/java/signalr/src/test/java/com/microsoft/signalr/NegotiateResponseTest.java
- clients/java/signalr/src/test/java/com/microsoft/signalr/WebSocketTransportTest.java
- clients/java/signalr/src/test/java/com/microsoft/signalr/sample/Chat.java
> [Java] Cleanup exceptions

- clients/java/signalr/src/main/java/com/microsoft/signalr/HttpHubConnectionBuilder.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/HubConnection.java
- clients/java/signalr/src/test/java/com/microsoft/signalr/HubConnectionTest.java
- clients/java/signalr/src/test/java/com/microsoft/signalr/NegotiateResponseTest.java
Adding ability to configure headers in the Java client.
Fixes: https://github.com/aspnet/SignalR/issues/3064
> [Java] Add ability to configure headers

- clients/java/signalr/src/main/java/com/microsoft/signalr/HubConnection.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/OkHttpWebSocketWrapper.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/WebSocketTransport.java
SLF4J Has different formatted log messaging logic.
You can see more here: https://www.slf4j.org/api/org/slf4j/helpers/MessageFormatter.html
> Update Formatted Log Messages

- clients/java/signalr/build.gradle
- clients/java/signalr/src/main/java/com/microsoft/signalr/HttpHubConnectionBuilder.java
Updating our `build.gradle` file to have explicit version numbers for our dependencies. Also making some APIs on the `HttpHubConnectionBuilder `package private
> Update dependency version numbers and HttpHubConnection APIs

- .vsts-pipelines/builds/ci-internal.yml
- .vsts-pipelines/builds/ci-public.yml
See https://github.com/aspnet/BuildTools/pull/812
> Update to new VSTS script

- clients/java/signalr/src/main/java/com/microsoft/signalr/Action.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/Action1.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/Action2.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/Action3.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/Action4.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/Action5.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/Action6.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/Action7.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/Action8.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/HttpHubConnectionBuilder.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/HubConnection.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/HubConnectionBuilder.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/HubConnectionState.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/HubException.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/Subscription.java
More Java Docs! Doing a another run of API docs work after the preview 3 changes.
Issue: https://github.com/aspnet/SignalR/issues/2982
> More Java Docs

- clients/java/signalr/src/main/java/com/microsoft/signalr/Action.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/Action1.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/Action2.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/Action3.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/Action4.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/Action5.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/Action6.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/Action7.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/Action8.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/ActionBase.java
I don't think the PR automation is working right now?
> Merge release/2.2 Remove functional interfaces (#3165)

- test/Microsoft.AspNetCore.SignalR.Tests/MapSignalRTests.cs
Fixes https://github.com/aspnet/SignalR/issues/3161
> Fix tests to use dynamic ports

- clients/java/signalr/src/main/java/com/microsoft/signalr/DefaultHttpClient.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/HttpClient.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/HubConnection.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/InvocationRequest.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/OkHttpWebSocketWrapper.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/Transport.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/WebSocketTransport.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/WebSocketWrapper.java
- clients/java/signalr/src/test/java/com/microsoft/signalr/HubConnectionTest.java
- clients/java/signalr/src/test/java/com/microsoft/signalr/MockTransport.java
- clients/java/signalr/src/test/java/com/microsoft/signalr/TestHttpClient.java
- clients/java/signalr/src/test/java/com/microsoft/signalr/WebSocketTransportTest.java
Fixes https://github.com/aspnet/SignalR/issues/3073
~~TODO: Write a couple tests verifying the hot vs. cold observable behavior of things like `hubConnection.start` and `hubConnection.stop`~~
We have tests that don't subscribe to start and verify things have happened and similarly for stop. Also verified manually.
> [Java] Plumb RxJava through client

- clients/java/signalr/src/main/java/com/microsoft/signalr/WebSocketTransport.java
- clients/java/signalr/src/test/java/com/microsoft/signalr/WebSocketTransportTest.java
Test for https://github.com/aspnet/SignalR/pull/3218
Will fail until we merge that PR
> [Java] Add null ref test for websocket

- clients/ts/FunctionalTests/Startup.cs
- clients/ts/FunctionalTests/TestHub.cs
- clients/ts/FunctionalTests/package-lock.json
- clients/ts/FunctionalTests/scripts/run-tests.ts
- clients/ts/FunctionalTests/ts/ConnectionTests.ts
- clients/ts/FunctionalTests/ts/HubConnectionTests.ts
- clients/ts/FunctionalTests/ts/LogBannerReporter.ts
- clients/ts/FunctionalTests/ts/WebSocketTests.ts
- clients/ts/FunctionalTests/webpack.config.js
- clients/ts/signalr-protocol-msgpack/package-lock.json
- clients/ts/signalr-protocol-msgpack/package.json
- clients/ts/signalr/package-lock.json
- clients/ts/signalr/package.json
- clients/ts/signalr/src/DefaultHttpClient.ts
- clients/ts/signalr/src/HttpClient.ts
- clients/ts/signalr/src/HttpConnection.ts
- clients/ts/signalr/src/NodeHttpClient.ts
- clients/ts/signalr/src/Polyfills.ts
- clients/ts/signalr/src/ServerSentEventsTransport.ts
- clients/ts/signalr/src/WebSocketTransport.ts
- clients/ts/signalr/tests/WebSocketTransport.test.ts
- clients/ts/signalr/webpack.config.js
Fixes https://github.com/aspnet/SignalR/issues/3192
> Enable cookie jar for Node client using request package

- clients/java/signalr/src/main/java/com/microsoft/signalr/Action5.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/HubConnection.java
Some things that I saw from scanning the new API docs
> Java API Doc revisions

- clients/java/signalr/src/main/java/com/microsoft/signalr/HubConnection.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/OkHttpWebSocketWrapper.java
- clients/java/signalr/src/test/java/com/microsoft/signalr/WebSocketTransportTest.java
- clients/ts/signalr/src/HttpConnection.ts
- clients/ts/signalr/src/HubConnection.ts
- clients/ts/signalr/src/LongPollingTransport.ts
- clients/ts/signalr/src/ServerSentEventsTransport.ts
- clients/ts/signalr/src/Utils.ts
- clients/ts/signalr/src/WebSocketTransport.ts
- clients/ts/signalr/src/XhrHttpClient.ts
- clients/ts/signalr/tests/HttpConnection.test.ts
- clients/ts/signalr/tests/WebSocketTransport.test.ts
Mostly just adding full stops to places, couple other touch ups.
> Clean up logging

- test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs
React to https://github.com/aspnet/Logging/pull/932
> Remove obsolete logging API usage

- test/Microsoft.AspNetCore.SignalR.StackExchangeRedis.Tests/Docker.cs
Forgot about StackExchange.Redis when making these changes.
Will merge when CI is green
FYI @muratg
> Add docker retry to stackexchange redis tests

- test/Microsoft.AspNetCore.SignalR.StackExchangeRedis.Tests/Docker.cs
> Merge master

- README.md
I realized there wasn't really a link to the docs on the README...
> Add docs blurb to Readme

- clients/ts/FunctionalTests/FunctionalTests.csproj
- clients/ts/FunctionalTests/Startup.cs
@muratg 2.2 Test only
@pranavkm In case you have any input.
> Custom CORS-like middleware to allow wildcard origin in test app

- test/Microsoft.AspNetCore.Http.Connections.Tests/HttpConnectionDispatcherTests.cs
- test/Microsoft.AspNetCore.Http.Connections.Tests/HttpConnectionManagerTests.cs
- test/Microsoft.AspNetCore.Http.Connections.Tests/LongPollingTests.cs
- test/Microsoft.AspNetCore.Http.Connections.Tests/ServerSentEventsTests.cs
- test/Microsoft.AspNetCore.Http.Connections.Tests/WebSocketsTests.cs
- test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs
- test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubProtocolVersionTests.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/HttpConnectionTests.ConnectionLifecycle.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/HttpConnectionTests.Transport.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/HttpConnectionTests.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/HubConnectionTests.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/LongPollingTransportTests.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/ServerSentEventsTransportTests.cs
- test/Microsoft.AspNetCore.SignalR.Redis.Tests/RedisEndToEnd.cs
- test/Microsoft.AspNetCore.SignalR.StackExchangeRedis.Tests/RedisEndToEnd.cs
- test/Microsoft.AspNetCore.SignalR.Tests.Utils/FunctionalTestBase.cs
- test/Microsoft.AspNetCore.SignalR.Tests.Utils/VerifiableLoggedTest.cs
- test/Microsoft.AspNetCore.SignalR.Tests.Utils/VerifyNoErrorsScope.cs
- test/Microsoft.AspNetCore.SignalR.Tests/EndToEndTests.cs
- test/Microsoft.AspNetCore.SignalR.Tests/HubConnectionHandlerTestUtils/Utils.cs
- test/Microsoft.AspNetCore.SignalR.Tests/HubConnectionHandlerTests.cs
- test/Microsoft.AspNetCore.SignalR.Tests/WebSocketsTransportTests.cs
Fixes #3274 
~~This is still WIP as there is some more cleanup I can do, and some tests fail since they have error logs I'll need to exclude.~~
@muratg FYI 2.2 test changes
> Add logging to HubConnectionHandlerTests

- clients/java/signalr/src/main/java/com/microsoft/signalr/CancelInvocationMessage.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/HubConnection.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/InvocationRequest.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/JsonHubProtocol.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/StreamInvocationMessage.java
- clients/java/signalr/src/main/java/com/microsoft/signalr/StreamItem.java
- clients/java/signalr/src/test/java/com/microsoft/signalr/HubConnectionTest.java
- clients/java/signalr/src/test/java/com/microsoft/signalr/JsonHubProtocolTest.java
~~Hacking stuff together atm.~~
Adding streaming support for the Java client. Also added the ability to cancel a StreamInvocation by disposing.
> Java Client Steaming 

- clients/ts/signalr/src/DefaultHttpClient.ts
- clients/ts/signalr/src/HttpConnection.ts
Fixes https://github.com/aspnet/SignalR/issues/3254
@muratg We'd like to discuss the release timeline for this fix as it's a broken scenario when using Angular 6+.
> Fix dynamic require for Webpack

- test/Microsoft.AspNetCore.SignalR.Client.Tests/HttpConnectionTests.ConnectionLifecycle.cs
- test/Microsoft.AspNetCore.SignalR.Client.Tests/ServerSentEventsTransportTests.cs
- version.props
> Reenable logging for SSE tests

- version.props
Reacting to https://github.com/aspnet/AspNetCore/pull/4171
> Set local builds to build as 3.0.0-dev
